// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package regblock_pkg;

    localparam REGBLOCK_DATA_WIDTH = 8;
    localparam REGBLOCK_MIN_ADDR_WIDTH = 5;
    localparam REGBLOCK_SIZE = 'h1e;

    typedef struct {
        logic [7:0] next;
    } top__ro_reg_rbuffer_trigger_1af3644f__f1__in_t;

    typedef struct {
        top__ro_reg_rbuffer_trigger_1af3644f__f1__in_t f1;
    } top__ro_reg_rbuffer_trigger_1af3644f__in_t;

    typedef struct {
        logic [7:0] next;
    } top__ro_reg_rbuffer_trigger_cba4ae9c__f1__in_t;

    typedef struct {
        top__ro_reg_rbuffer_trigger_cba4ae9c__f1__in_t f1;
    } top__ro_reg_rbuffer_trigger_cba4ae9c__in_t;

    typedef struct {
        logic rd_ack;
        logic [7:0] rd_data;
    } top__myreg_wide__external__in_t;

    typedef struct {
        logic rd_ack;
        logic [7:0] rd_data;
        logic wr_ack;
    } top__ext_block__external__in_t;

    typedef struct {
        logic incr_en;
        logic trigger_sig;
        logic trigger_sig_n;
        top__ro_reg_rbuffer_trigger_1af3644f__in_t g3_r1;
        top__ro_reg_rbuffer_trigger_cba4ae9c__in_t g3_r2;
        top__myreg_wide__external__in_t ext_reg1;
        top__ext_block__external__in_t ext_block;
    } regblock__in_t;

    typedef struct {
        logic [2:0] value;
    } top__reg1__f1__out_t;

    typedef struct {
        logic [2:0] value;
    } top__reg1__f2__out_t;

    typedef struct {
        logic [2:0] value;
    } top__reg1__f3__out_t;

    typedef struct {
        logic [2:0] value;
    } top__reg1__f4__out_t;

    typedef struct {
        logic [2:0] value;
    } top__reg1__f5__out_t;

    typedef struct {
        logic [2:0] value;
    } top__reg1__f6__out_t;

    typedef struct {
        logic [2:0] value;
    } top__reg1__f7__out_t;

    typedef struct {
        logic [2:0] value;
    } top__reg1__f8__out_t;

    typedef struct {
        logic [2:0] value;
    } top__reg1__f9__out_t;

    typedef struct {
        logic [2:0] value;
    } top__reg1__fa__out_t;

    typedef struct {
        top__reg1__f1__out_t f1;
        top__reg1__f2__out_t f2;
        top__reg1__f3__out_t f3;
        top__reg1__f4__out_t f4;
        top__reg1__f5__out_t f5;
        top__reg1__f6__out_t f6;
        top__reg1__f7__out_t f7;
        top__reg1__f8__out_t f8;
        top__reg1__f9__out_t f9;
        top__reg1__fa__out_t fa;
    } top__reg1__out_t;

    typedef struct {
        logic [2:0] value;
    } top__reg1_msb0__fa__out_t;

    typedef struct {
        logic [2:0] value;
    } top__reg1_msb0__f9__out_t;

    typedef struct {
        logic [2:0] value;
    } top__reg1_msb0__f8__out_t;

    typedef struct {
        logic [2:0] value;
    } top__reg1_msb0__f7__out_t;

    typedef struct {
        logic [2:0] value;
    } top__reg1_msb0__f6__out_t;

    typedef struct {
        logic [2:0] value;
    } top__reg1_msb0__f5__out_t;

    typedef struct {
        logic [2:0] value;
    } top__reg1_msb0__f4__out_t;

    typedef struct {
        logic [2:0] value;
    } top__reg1_msb0__f3__out_t;

    typedef struct {
        logic [2:0] value;
    } top__reg1_msb0__f2__out_t;

    typedef struct {
        logic [2:0] value;
    } top__reg1_msb0__f1__out_t;

    typedef struct {
        top__reg1_msb0__fa__out_t fa;
        top__reg1_msb0__f9__out_t f9;
        top__reg1_msb0__f8__out_t f8;
        top__reg1_msb0__f7__out_t f7;
        top__reg1_msb0__f6__out_t f6;
        top__reg1_msb0__f5__out_t f5;
        top__reg1_msb0__f4__out_t f4;
        top__reg1_msb0__f3__out_t f3;
        top__reg1_msb0__f2__out_t f2;
        top__reg1_msb0__f1__out_t f1;
    } top__reg1_msb0__out_t;

    typedef struct {
        logic [4:0] value;
    } top__reg2__f1__out_t;

    typedef struct {
        logic [4:0] value;
    } top__reg2__f2__out_t;

    typedef struct {
        logic [4:0] value;
    } top__reg2__f3__out_t;

    typedef struct {
        logic [4:0] value;
    } top__reg2__f4__out_t;

    typedef struct {
        top__reg2__f1__out_t f1;
        top__reg2__f2__out_t f2;
        top__reg2__f3__out_t f3;
        top__reg2__f4__out_t f4;
    } top__reg2__out_t;

    typedef struct {
        logic [7:0] value;
    } top__myreg__f1__out_t;

    typedef struct {
        top__myreg__f1__out_t f1;
    } top__myreg__out_t;

    typedef struct {
        logic [7:0] value;
    } top__myreg_rbuffer_trigger_83265e99__f1__out_t;

    typedef struct {
        top__myreg_rbuffer_trigger_83265e99__f1__out_t f1;
    } top__myreg_rbuffer_trigger_83265e99__out_t;

    typedef struct {
        logic [15:0] value;
    } top__myreg_wide__f1__out_t;

    typedef struct {
        top__myreg_wide__f1__out_t f1;
    } top__myreg_wide__out_t;

    typedef struct {
        logic [15:0] value;
    } top__myreg_wide_rbuffer_trigger_139423f7__f1__out_t;

    typedef struct {
        top__myreg_wide_rbuffer_trigger_139423f7__f1__out_t f1;
    } top__myreg_wide_rbuffer_trigger_139423f7__out_t;

    typedef struct {
        logic value;
    } top__g4_trig__trig__out_t;

    typedef struct {
        top__g4_trig__trig__out_t trig;
    } top__g4_trig__out_t;

    typedef struct {
        logic [7:0] value;
    } top__myreg_rbuffer_trigger_70dca40f__f1__out_t;

    typedef struct {
        top__myreg_rbuffer_trigger_70dca40f__f1__out_t f1;
    } top__myreg_rbuffer_trigger_70dca40f__out_t;

    typedef struct {
        logic [7:0] value;
    } top__myreg_rbuffer_trigger_82f767f6__f1__out_t;

    typedef struct {
        top__myreg_rbuffer_trigger_82f767f6__f1__out_t f1;
    } top__myreg_rbuffer_trigger_82f767f6__out_t;

    typedef struct {
        logic [1:0] req;
        logic req_is_wr;
    } top__myreg_wide__external__out_t;

    typedef struct {
        logic req;
        logic addr;
        logic req_is_wr;
        logic [7:0] wr_data;
        logic [7:0] wr_biten;
    } top__ext_block__external__out_t;

    typedef struct {
        top__reg1__out_t reg1;
        top__reg1_msb0__out_t reg1_msb0;
        top__reg2__out_t reg2;
        top__myreg__out_t g1_r1;
        top__myreg_rbuffer_trigger_83265e99__out_t g1_r2;
        top__myreg_wide__out_t g2_r1;
        top__myreg_wide_rbuffer_trigger_139423f7__out_t g2_r2;
        top__g4_trig__out_t g4_trig;
        top__myreg_rbuffer_trigger_70dca40f__out_t g4_r1;
        top__myreg_rbuffer_trigger_82f767f6__out_t g4_r2;
        top__myreg_wide__external__out_t ext_reg1;
        top__ext_block__external__out_t ext_block;
    } regblock__out_t;
endpackage
