# Dependabot configuration for automatic dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Monitor GitHub Actions for version updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    # Group all GitHub Actions updates into a single PR
    groups:
      github-actions:
        patterns:
          - "*"
    # Automatically rebase PRs when conflicts occur
    rebase-strategy: "auto"

  # Monitor Python dependencies in requirements.txt
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    # Group Python dependency updates
    groups:
      python-dependencies:
        patterns:
          - "*"
    rebase-strategy: "auto"

  # Monitor Python dependencies in docs/requirements.txt
  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
      - "documentation"
    groups:
      docs-dependencies:
        patterns:
          - "*"
    rebase-strategy: "auto"
