// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package regblock_pkg;

    localparam REGBLOCK_DATA_WIDTH = 16;
    localparam REGBLOCK_MIN_ADDR_WIDTH = 6;
    localparam REGBLOCK_SIZE = 'h3c;

    typedef struct {
        logic [7:0] next;
    } top__r_reg__f1__in_t;

    typedef struct {
        logic [10:0] next;
    } top__r_reg__f2__in_t;

    typedef struct {
        top__r_reg__f1__in_t f1;
        top__r_reg__f2__in_t f2;
    } top__r_reg__in_t;

    typedef struct {
        logic [7:0] next;
    } top__r_reg_lsb0__f1__in_t;

    typedef struct {
        logic [10:0] next;
    } top__r_reg_lsb0__f2__in_t;

    typedef struct {
        top__r_reg_lsb0__f1__in_t f1;
        top__r_reg_lsb0__f2__in_t f2;
    } top__r_reg_lsb0__in_t;

    typedef struct {
        logic [19:0] next;
    } top__r_reg2__f1__in_t;

    typedef struct {
        logic [1:0] next;
    } top__r_reg2__f2__in_t;

    typedef struct {
        top__r_reg2__f1__in_t f1;
        top__r_reg2__f2__in_t f2;
    } top__r_reg2__in_t;

    typedef struct {
        top__r_reg__in_t r_reg;
        top__r_reg_lsb0__in_t r_reg_lsb0;
        top__r_reg2__in_t r_reg2;
    } regblock__in_t;

    typedef struct {
        logic [7:0] value;
    } top__rw_reg1__f1__out_t;

    typedef struct {
        logic [2:0] value;
    } top__rw_reg1__f2__out_t;

    typedef struct {
        logic value;
    } top__rw_reg1__f3__out_t;

    typedef struct {
        logic [7:0] value;
    } top__rw_reg1__f4__out_t;

    typedef struct {
        top__rw_reg1__f1__out_t f1;
        top__rw_reg1__f2__out_t f2;
        top__rw_reg1__f3__out_t f3;
        top__rw_reg1__f4__out_t f4;
    } top__rw_reg1__out_t;

    typedef struct {
        logic [3:0] value;
    } top__rw_reg2__f1__out_t;

    typedef struct {
        logic [15:0] value;
    } top__rw_reg2__f2__out_t;

    typedef struct {
        top__rw_reg2__f1__out_t f1;
        top__rw_reg2__f2__out_t f2;
    } top__rw_reg2__out_t;

    typedef struct {
        logic [7:0] value;
    } top__rw_reg1_lsb0__f1__out_t;

    typedef struct {
        logic [2:0] value;
    } top__rw_reg1_lsb0__f2__out_t;

    typedef struct {
        logic value;
    } top__rw_reg1_lsb0__f3__out_t;

    typedef struct {
        logic [7:0] value;
    } top__rw_reg1_lsb0__f4__out_t;

    typedef struct {
        top__rw_reg1_lsb0__f1__out_t f1;
        top__rw_reg1_lsb0__f2__out_t f2;
        top__rw_reg1_lsb0__f3__out_t f3;
        top__rw_reg1_lsb0__f4__out_t f4;
    } top__rw_reg1_lsb0__out_t;

    typedef struct {
        logic [3:0] value;
    } top__rw_reg2_lsb0__f1__out_t;

    typedef struct {
        logic [15:0] value;
    } top__rw_reg2_lsb0__f2__out_t;

    typedef struct {
        top__rw_reg2_lsb0__f1__out_t f1;
        top__rw_reg2_lsb0__f2__out_t f2;
    } top__rw_reg2_lsb0__out_t;

    typedef struct {
        logic value;
    } top__r_reg__f0__out_t;

    typedef struct {
        top__r_reg__f0__out_t f0;
    } top__r_reg__out_t;

    typedef struct {
        logic [31:0] value;
    } top__r_reg3__f1__out_t;

    typedef struct {
        top__r_reg3__f1__out_t f1;
    } top__r_reg3__out_t;

    typedef struct {
        logic [31:0] value;
    } top__r_reg4__f1__out_t;

    typedef struct {
        top__r_reg4__f1__out_t f1;
    } top__r_reg4__out_t;

    typedef struct {
        top__rw_reg1__out_t rw_reg1;
        top__rw_reg2__out_t rw_reg2;
        top__rw_reg1_lsb0__out_t rw_reg1_lsb0;
        top__rw_reg2_lsb0__out_t rw_reg2_lsb0;
        top__r_reg__out_t r_reg;
        top__r_reg3__out_t r_reg3;
        top__r_reg4__out_t r_reg4;
    } regblock__out_t;
endpackage
