// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package regblock_pkg;

    localparam REGBLOCK_DATA_WIDTH = 32;
    localparam REGBLOCK_MIN_ADDR_WIDTH = 6;
    localparam REGBLOCK_SIZE = 'h38;

    typedef struct packed {
        logic [31:0] f;
    } top__er_rw__external__fields__in_t;

    typedef struct {
        logic rd_ack;
        top__er_rw__external__fields__in_t rd_data;
        logic wr_ack;
    } top__er_rw__external__in_t;

    typedef struct packed {
        logic [31:0] f;
    } top__er_r__external__fields__in_t;

    typedef struct {
        logic rd_ack;
        top__er_r__external__fields__in_t rd_data;
    } top__er_r__external__in_t;

    typedef struct {
        logic wr_ack;
    } top__er_w__external__in_t;

    typedef struct {
        logic rd_ack;
        logic [31:0] rd_data;
        logic wr_ack;
    } top__mem_rw__external__in_t;

    typedef struct {
        logic rd_ack;
        logic [31:0] rd_data;
        logic wr_ack;
    } top__mem_r__external__in_t;

    typedef struct {
        logic rd_ack;
        logic [31:0] rd_data;
        logic wr_ack;
    } top__mem_w__external__in_t;

    typedef struct {
        top__er_rw__external__in_t er_rw;
        top__er_r__external__in_t er_r;
        top__er_w__external__in_t er_w;
        top__mem_rw__external__in_t mem_rw;
        top__mem_r__external__in_t mem_r;
        top__mem_w__external__in_t mem_w;
    } regblock__in_t;

    typedef struct {
        logic [31:0] value;
    } top__r_w__f__out_t;

    typedef struct {
        top__r_w__f__out_t f;
    } top__r_w__out_t;

    typedef struct packed {
        logic [31:0] f;
    } top__er_rw__external__fields__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
        top__er_rw__external__fields__out_t wr_data;
        top__er_rw__external__fields__out_t wr_biten;
    } top__er_rw__external__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
    } top__er_r__external__out_t;

    typedef struct packed {
        logic [31:0] f;
    } top__er_w__external__fields__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
        top__er_w__external__fields__out_t wr_data;
        top__er_w__external__fields__out_t wr_biten;
    } top__er_w__external__out_t;

    typedef struct {
        logic req;
        logic [2:0] addr;
        logic req_is_wr;
        logic [31:0] wr_data;
        logic [31:0] wr_biten;
    } top__mem_rw__external__out_t;

    typedef struct {
        logic req;
        logic [2:0] addr;
        logic req_is_wr;
        logic [31:0] wr_data;
        logic [31:0] wr_biten;
    } top__mem_r__external__out_t;

    typedef struct {
        logic req;
        logic [2:0] addr;
        logic req_is_wr;
        logic [31:0] wr_data;
        logic [31:0] wr_biten;
    } top__mem_w__external__out_t;

    typedef struct {
        top__r_w__out_t r_w;
        top__er_rw__external__out_t er_rw;
        top__er_r__external__out_t er_r;
        top__er_w__external__out_t er_w;
        top__mem_rw__external__out_t mem_rw;
        top__mem_r__external__out_t mem_r;
        top__mem_w__external__out_t mem_w;
    } regblock__out_t;
endpackage
