// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module regblock (
        input wire clk,
        input wire rst,

        input wire s_apb_psel,
        input wire s_apb_penable,
        input wire s_apb_pwrite,
        input wire [2:0] s_apb_pprot,
        input wire [5:0] s_apb_paddr,
        input wire [31:0] s_apb_pwdata,
        input wire [3:0] s_apb_pstrb,
        output logic s_apb_pready,
        output logic [31:0] s_apb_prdata,
        output logic s_apb_pslverr,

        input regblock_pkg::regblock__in_t hwif_in,
        output regblock_pkg::regblock__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [5:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Request
    logic is_active;
    always_ff @(posedge clk) begin
        if(rst) begin
            is_active <= '0;
            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
            cpuif_wr_biten <= '0;
        end else begin
            if(~is_active) begin
                if(s_apb_psel) begin
                    is_active <= '1;
                    cpuif_req <= '1;
                    cpuif_req_is_wr <= s_apb_pwrite;
                    cpuif_addr <= {s_apb_paddr[5:2], 2'b0};
                    cpuif_wr_data <= s_apb_pwdata;
                    for(int i=0; i<4; i++) begin
                        cpuif_wr_biten[i*8 +: 8] <= {8{s_apb_pstrb[i]}};
                    end
                end
            end else begin
                cpuif_req <= '0;
                if(cpuif_rd_ack || cpuif_wr_ack) begin
                    is_active <= '0;
                end
            end
        end
    end

    // Response
    assign s_apb_pready = cpuif_rd_ack | cpuif_wr_ack;
    assign s_apb_prdata = cpuif_rd_data;
    assign s_apb_pslverr = cpuif_rd_err | cpuif_wr_err;

    logic cpuif_req_masked;
    logic external_req;
    logic external_pending;
    logic external_wr_ack;
    logic external_rd_ack;
    always_ff @(posedge clk) begin
        if(rst) begin
            external_pending <= '0;
        end else begin
            if(external_req & ~external_wr_ack & ~external_rd_ack) external_pending <= '1;
            else if(external_wr_ack | external_rd_ack) external_pending <= '0;
            `ifndef SYNTHESIS
                assert_bad_ext_wr_ack: assert(!external_wr_ack || (external_pending | external_req))
                    else $error("An external wr_ack strobe was asserted when no external request was active");
                assert_bad_ext_rd_ack: assert(!external_rd_ack || (external_pending | external_req))
                    else $error("An external rd_ack strobe was asserted when no external request was active");
            `endif
        end
    end

    // Read & write latencies are balanced. Stalls not required
    // except if external
    assign cpuif_req_stall_rd = external_pending;
    assign cpuif_req_stall_wr = external_pending;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic r_rw;
        logic r_r;
        logic r_w;
        logic er_rw;
        logic er_r;
        logic er_w;
        logic mem_rw;
        logic mem_r;
        logic mem_w;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic decoded_strb_is_external;

    logic [5:0] decoded_addr;

    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_invalid_rw;
        automatic logic is_external;
        is_external = '0;
        is_valid_addr = '0;
        is_invalid_rw = '0;
        decoded_reg_strb.r_rw = cpuif_req_masked & (cpuif_addr == 6'h0);
        is_valid_addr |= cpuif_req_masked & (cpuif_addr == 6'h0);
        is_invalid_rw |= '0;
        decoded_reg_strb.r_r = cpuif_req_masked & (cpuif_addr == 6'h4) & !cpuif_req_is_wr;
        is_valid_addr |= cpuif_req_masked & (cpuif_addr == 6'h4);
        is_invalid_rw |= cpuif_req_masked & (cpuif_addr == 6'h4) & cpuif_req_is_wr;
        decoded_reg_strb.r_w = cpuif_req_masked & (cpuif_addr == 6'h8) & cpuif_req_is_wr;
        is_valid_addr |= cpuif_req_masked & (cpuif_addr == 6'h8);
        is_invalid_rw |= cpuif_req_masked & (cpuif_addr == 6'h8) & !cpuif_req_is_wr;
        decoded_reg_strb.er_rw = cpuif_req_masked & (cpuif_addr == 6'hc);
        is_external |= cpuif_req_masked & (cpuif_addr == 6'hc);
        is_valid_addr |= cpuif_req_masked & (cpuif_addr == 6'hc);
        is_invalid_rw |= '0;
        decoded_reg_strb.er_r = cpuif_req_masked & (cpuif_addr == 6'h10) & !cpuif_req_is_wr;
        is_external |= cpuif_req_masked & (cpuif_addr == 6'h10) & !cpuif_req_is_wr;
        is_valid_addr |= cpuif_req_masked & (cpuif_addr == 6'h10);
        is_invalid_rw |= cpuif_req_masked & (cpuif_addr == 6'h10) & cpuif_req_is_wr;
        decoded_reg_strb.er_w = cpuif_req_masked & (cpuif_addr == 6'h14) & cpuif_req_is_wr;
        is_external |= cpuif_req_masked & (cpuif_addr == 6'h14) & cpuif_req_is_wr;
        is_valid_addr |= cpuif_req_masked & (cpuif_addr == 6'h14);
        is_invalid_rw |= cpuif_req_masked & (cpuif_addr == 6'h14) & !cpuif_req_is_wr;
        decoded_reg_strb.mem_rw = cpuif_req_masked & (cpuif_addr >= 6'h20) & (cpuif_addr <= 6'h20 + 6'h7);
        is_external |= cpuif_req_masked & (cpuif_addr >= 6'h20) & (cpuif_addr <= 6'h20 + 6'h7);
        is_valid_addr |= cpuif_req_masked & (cpuif_addr >= 6'h20) & (cpuif_addr <= 6'h20 + 6'h7);
        is_invalid_rw |= '0;
        decoded_reg_strb.mem_r = cpuif_req_masked & (cpuif_addr >= 6'h28) & (cpuif_addr <= 6'h28 + 6'h7) & !cpuif_req_is_wr;
        is_external |= cpuif_req_masked & (cpuif_addr >= 6'h28) & (cpuif_addr <= 6'h28 + 6'h7) & !cpuif_req_is_wr;
        is_valid_addr |= cpuif_req_masked & (cpuif_addr >= 6'h28) & (cpuif_addr <= 6'h28 + 6'h7);
        is_invalid_rw |= cpuif_req_masked & (cpuif_addr >= 6'h28) & (cpuif_addr <= 6'h28 + 6'h7) & cpuif_req_is_wr;
        decoded_reg_strb.mem_w = cpuif_req_masked & (cpuif_addr >= 6'h30) & (cpuif_addr <= 6'h30 + 6'h7) & cpuif_req_is_wr;
        is_external |= cpuif_req_masked & (cpuif_addr >= 6'h30) & (cpuif_addr <= 6'h30 + 6'h7) & cpuif_req_is_wr;
        is_valid_addr |= cpuif_req_masked & (cpuif_addr >= 6'h30) & (cpuif_addr <= 6'h30 + 6'h7);
        is_invalid_rw |= cpuif_req_masked & (cpuif_addr >= 6'h30) & (cpuif_addr <= 6'h30 + 6'h7) & !cpuif_req_is_wr;
        decoded_err = (~is_valid_addr | is_invalid_rw) & decoded_req;
        decoded_strb_is_external = is_external;
        external_req = is_external;
    end

    // Pass down signals to next stage
    assign decoded_addr = cpuif_addr;

    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } f;
        } r_rw;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } f;
        } r_w;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic [31:0] value;
            } f;
        } r_rw;
        struct {
            struct {
                logic [31:0] value;
            } f;
        } r_w;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: regblock.r_rw.f
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.r_rw.f.value;
        load_next_c = '0;
        if(decoded_reg_strb.r_rw && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.r_rw.f.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.r_rw.f.next = next_c;
        field_combo.r_rw.f.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.r_rw.f.value <= 32'h28;
        end else begin
            if(field_combo.r_rw.f.load_next) begin
                field_storage.r_rw.f.value <= field_combo.r_rw.f.next;
            end
        end
    end
    // Field: regblock.r_w.f
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.r_w.f.value;
        load_next_c = '0;
        if(decoded_reg_strb.r_w && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.r_w.f.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.r_w.f.next = next_c;
        field_combo.r_w.f.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.r_w.f.value <= 32'h64;
        end else begin
            if(field_combo.r_w.f.load_next) begin
                field_storage.r_w.f.value <= field_combo.r_w.f.next;
            end
        end
    end
    assign hwif_out.r_w.f.value = field_storage.r_w.f.value;
    // External register: regblock.er_rw
    assign hwif_out.er_rw.req = decoded_reg_strb.er_rw;
    assign hwif_out.er_rw.req_is_wr = decoded_req_is_wr;
    assign hwif_out.er_rw.wr_data = decoded_wr_data;
    assign hwif_out.er_rw.wr_biten = decoded_wr_biten;
    // External register: regblock.er_r

    assign hwif_out.er_r.req = !decoded_req_is_wr ? decoded_reg_strb.er_r : '0;
    assign hwif_out.er_r.req_is_wr = decoded_req_is_wr;
    // External register: regblock.er_w

    assign hwif_out.er_w.req = decoded_req_is_wr ? decoded_reg_strb.er_w : '0;
    assign hwif_out.er_w.req_is_wr = decoded_req_is_wr;
    assign hwif_out.er_w.wr_data = decoded_wr_data;
    assign hwif_out.er_w.wr_biten = decoded_wr_biten;
    // External region: regblock.mem_rw
    assign hwif_out.mem_rw.req = decoded_reg_strb.mem_rw;
    assign hwif_out.mem_rw.addr = decoded_addr[2:0];
    assign hwif_out.mem_rw.req_is_wr = decoded_req_is_wr;
    assign hwif_out.mem_rw.wr_data = decoded_wr_data;
    assign hwif_out.mem_rw.wr_biten = decoded_wr_biten;
    // External region: regblock.mem_r
    assign hwif_out.mem_r.req = decoded_reg_strb.mem_r;
    assign hwif_out.mem_r.addr = decoded_addr[2:0];
    assign hwif_out.mem_r.req_is_wr = decoded_req_is_wr;
    assign hwif_out.mem_r.wr_data = decoded_wr_data;
    assign hwif_out.mem_r.wr_biten = decoded_wr_biten;
    // External region: regblock.mem_w
    assign hwif_out.mem_w.req = decoded_reg_strb.mem_w;
    assign hwif_out.mem_w.addr = decoded_addr[2:0];
    assign hwif_out.mem_w.req_is_wr = decoded_req_is_wr;
    assign hwif_out.mem_w.wr_data = decoded_wr_data;
    assign hwif_out.mem_w.wr_biten = decoded_wr_biten;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    always_comb begin
        automatic logic wr_ack;
        wr_ack = '0;
        wr_ack |= hwif_in.er_rw.wr_ack;
        wr_ack |= hwif_in.er_w.wr_ack;
        wr_ack |= hwif_in.mem_rw.wr_ack;
        wr_ack |= hwif_in.mem_r.wr_ack;
        wr_ack |= hwif_in.mem_w.wr_ack;
        external_wr_ack = wr_ack;
    end
    assign cpuif_wr_ack = external_wr_ack | (decoded_req & decoded_req_is_wr & ~decoded_strb_is_external);
    // Writes are always granted with no error response
    assign cpuif_wr_err = decoded_err;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------
    logic readback_external_rd_ack_c;
    always_comb begin
        automatic logic rd_ack;
        rd_ack = '0;
        rd_ack |= hwif_in.er_rw.rd_ack;
        rd_ack |= hwif_in.er_r.rd_ack;
        rd_ack |= hwif_in.mem_rw.rd_ack;
        rd_ack |= hwif_in.mem_r.rd_ack;
        rd_ack |= hwif_in.mem_w.rd_ack;
        readback_external_rd_ack_c = rd_ack;
    end

    logic readback_external_rd_ack;

    assign readback_external_rd_ack = readback_external_rd_ack_c;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;

    // Assign readback values to a flattened array
    logic [31:0] readback_array[7];
    assign readback_array[0][31:0] = (decoded_reg_strb.r_rw && !decoded_req_is_wr) ? field_storage.r_rw.f.value : '0;
    assign readback_array[1][31:0] = (decoded_reg_strb.r_r && !decoded_req_is_wr) ? 32'h50 : '0;
    assign readback_array[2] = hwif_in.er_rw.rd_ack ? hwif_in.er_rw.rd_data : '0;
    assign readback_array[3] = hwif_in.er_r.rd_ack ? hwif_in.er_r.rd_data : '0;
    assign readback_array[4] = hwif_in.mem_rw.rd_ack ? hwif_in.mem_rw.rd_data : '0;
    assign readback_array[5] = hwif_in.mem_r.rd_ack ? hwif_in.mem_r.rd_data : '0;
    assign readback_array[6] = hwif_in.mem_w.rd_ack ? hwif_in.mem_w.rd_data : '0;

    // Reduce the array
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr & ~decoded_strb_is_external;
        readback_err = decoded_err;
        readback_data_var = '0;
        for(int i=0; i<7; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign external_rd_ack = readback_external_rd_ack;
    assign cpuif_rd_ack = readback_done | readback_external_rd_ack;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
