// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package regblock_pkg;

    localparam REGBLOCK_DATA_WIDTH = 32;
    localparam REGBLOCK_MIN_ADDR_WIDTH = 3;
    localparam REGBLOCK_SIZE = 'h4;

    typedef struct {
        logic value;
    } top__r1__f__out_t;

    typedef struct {
        top__r1__f__out_t f;
    } top__r1__out_t;

    typedef struct {
        top__r1__out_t r1;
    } regblock__out_t;
endpackage
