// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module top (
        input wire clk,
        input wire rst,

        input wire s_apb_psel,
        input wire s_apb_penable,
        input wire s_apb_pwrite,
        input wire [2:0] s_apb_pprot,
        input wire [14:0] s_apb_paddr,
        input wire [31:0] s_apb_pwdata,
        input wire [3:0] s_apb_pstrb,
        output logic s_apb_pready,
        output logic [31:0] s_apb_prdata,
        output logic s_apb_pslverr,

        input top_pkg::top__in_t hwif_in,
        output top_pkg::top__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [14:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Request
    logic is_active;
    always_ff @(posedge clk) begin
        if(rst) begin
            is_active <= '0;
            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
            cpuif_wr_biten <= '0;
        end else begin
            if(~is_active) begin
                if(s_apb_psel) begin
                    is_active <= '1;
                    cpuif_req <= '1;
                    cpuif_req_is_wr <= s_apb_pwrite;
                    cpuif_addr <= {s_apb_paddr[14:2], 2'b0};
                    cpuif_wr_data <= s_apb_pwdata;
                    for(int i=0; i<4; i++) begin
                        cpuif_wr_biten[i*8 +: 8] <= {8{s_apb_pstrb[i]}};
                    end
                end
            end else begin
                cpuif_req <= '0;
                if(cpuif_rd_ack || cpuif_wr_ack) begin
                    is_active <= '0;
                end
            end
        end
    end

    // Response
    assign s_apb_pready = cpuif_rd_ack | cpuif_wr_ack;
    assign s_apb_prdata = cpuif_rd_data;
    assign s_apb_pslverr = cpuif_rd_err | cpuif_wr_err;

    logic cpuif_req_masked;
    logic external_req;
    logic external_pending;
    logic external_wr_ack;
    logic external_rd_ack;
    always_ff @(posedge clk) begin
        if(rst) begin
            external_pending <= '0;
        end else begin
            if(external_req & ~external_wr_ack & ~external_rd_ack) external_pending <= '1;
            else if(external_wr_ack | external_rd_ack) external_pending <= '0;
            assert(!external_wr_ack || (external_pending | external_req))
                else $error("An external wr_ack strobe was asserted when no external request was active");
            assert(!external_rd_ack || (external_pending | external_req))
                else $error("An external rd_ack strobe was asserted when no external request was active");
        end
    end

    // Read & write latencies are balanced. Stalls not required
    // except if external
    assign cpuif_req_stall_rd = external_pending;
    assign cpuif_req_stall_wr = external_pending;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic ext_reg;
        logic ext_ret;
        logic ext_rex;
        logic ext_rew;
        logic ext_rez;
        logic ext_rea;
        logic ext_reg_array[64];
        logic ext_rea_array[8];
        logic [1:0] wide_ext_reg;
        logic [1:0] wide_ext_reg_array[8];
        logic ext_rea_yyyay[3][5];
        logic rf;
        logic rx;
        logic mm;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_strb_is_external;

    logic [14:0] decoded_addr;

    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_external;
        is_external = '0;
        decoded_reg_strb.ext_reg = cpuif_req_masked & (cpuif_addr == 15'h0);
        is_external |= cpuif_req_masked & (cpuif_addr == 15'h0) & !cpuif_req_is_wr;
        decoded_reg_strb.ext_ret = cpuif_req_masked & (cpuif_addr == 15'h4);
        is_external |= cpuif_req_masked & (cpuif_addr == 15'h4) & !cpuif_req_is_wr;
        decoded_reg_strb.ext_rex = cpuif_req_masked & (cpuif_addr == 15'h8);
        is_external |= cpuif_req_masked & (cpuif_addr == 15'h8) & !cpuif_req_is_wr;
        decoded_reg_strb.ext_rew = cpuif_req_masked & (cpuif_addr == 15'hc);
        is_external |= cpuif_req_masked & (cpuif_addr == 15'hc);
        decoded_reg_strb.ext_rez = cpuif_req_masked & (cpuif_addr == 15'h10);
        is_external |= cpuif_req_masked & (cpuif_addr == 15'h10) & cpuif_req_is_wr;
        decoded_reg_strb.ext_rea = cpuif_req_masked & (cpuif_addr == 15'h14);
        is_external |= cpuif_req_masked & (cpuif_addr == 15'h14);
        for(int i0=0; i0<64; i0++) begin
            decoded_reg_strb.ext_reg_array[i0] = cpuif_req_masked & (cpuif_addr == 15'h100 + i0*15'h4);
            is_external |= cpuif_req_masked & (cpuif_addr == 15'h100 + i0*15'h4) & !cpuif_req_is_wr;
        end
        for(int i0=0; i0<8; i0++) begin
            decoded_reg_strb.ext_rea_array[i0] = cpuif_req_masked & (cpuif_addr == 15'h200 + i0*15'h4);
            is_external |= cpuif_req_masked & (cpuif_addr == 15'h200 + i0*15'h4);
        end
        decoded_reg_strb.wide_ext_reg[0] = cpuif_req_masked & (cpuif_addr == 15'h300);
        is_external |= cpuif_req_masked & (cpuif_addr == 15'h300);
        decoded_reg_strb.wide_ext_reg[1] = cpuif_req_masked & (cpuif_addr == 15'h304);
        is_external |= cpuif_req_masked & (cpuif_addr == 15'h304);
        for(int i0=0; i0<8; i0++) begin
            decoded_reg_strb.wide_ext_reg_array[i0][0] = cpuif_req_masked & (cpuif_addr == 15'h400 + i0*15'h8);
            is_external |= cpuif_req_masked & (cpuif_addr == 15'h400 + i0*15'h8);
            decoded_reg_strb.wide_ext_reg_array[i0][1] = cpuif_req_masked & (cpuif_addr == 15'h404 + i0*15'h8);
            is_external |= cpuif_req_masked & (cpuif_addr == 15'h404 + i0*15'h8);
        end
        for(int i0=0; i0<3; i0++) begin
            for(int i1=0; i1<5; i1++) begin
                decoded_reg_strb.ext_rea_yyyay[i0][i1] = cpuif_req_masked & (cpuif_addr == 15'h600 + i0*15'h14 + i1*15'h4);
                is_external |= cpuif_req_masked & (cpuif_addr == 15'h600 + i0*15'h14 + i1*15'h4);
            end
        end
        decoded_reg_strb.rf = cpuif_req_masked & (cpuif_addr >= 15'h1000) & (cpuif_addr <= 15'h1000 + 15'h1f);
        is_external |= cpuif_req_masked & (cpuif_addr >= 15'h1000) & (cpuif_addr <= 15'h1000 + 15'h1f);
        decoded_reg_strb.rx = cpuif_req_masked & (cpuif_addr >= 15'h2000) & (cpuif_addr <= 15'h2000 + 15'h1f);
        is_external |= cpuif_req_masked & (cpuif_addr >= 15'h2000) & (cpuif_addr <= 15'h2000 + 15'h1f);
        decoded_reg_strb.mm = cpuif_req_masked & (cpuif_addr >= 15'h4000) & (cpuif_addr <= 15'h4000 + 15'h1f);
        is_external |= cpuif_req_masked & (cpuif_addr >= 15'h4000) & (cpuif_addr <= 15'h4000 + 15'h1f);
        decoded_strb_is_external = is_external;
        external_req = is_external;
    end

    // Pass down signals to next stage
    assign decoded_addr = cpuif_addr;

    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------





    assign hwif_out.ext_reg.req = !decoded_req_is_wr ? decoded_reg_strb.ext_reg : '0;
    assign hwif_out.ext_reg.req_is_wr = decoded_req_is_wr;

    assign hwif_out.ext_ret.req = !decoded_req_is_wr ? decoded_reg_strb.ext_ret : '0;
    assign hwif_out.ext_ret.req_is_wr = decoded_req_is_wr;

    assign hwif_out.ext_rex.req = !decoded_req_is_wr ? decoded_reg_strb.ext_rex : '0;
    assign hwif_out.ext_rex.req_is_wr = decoded_req_is_wr;

    assign hwif_out.ext_rew.req = decoded_reg_strb.ext_rew;
    assign hwif_out.ext_rew.req_is_wr = decoded_req_is_wr;
    assign hwif_out.ext_rew.wr_data = decoded_wr_data;
    assign hwif_out.ext_rew.wr_biten = decoded_wr_biten;

    assign hwif_out.ext_rez.req = decoded_req_is_wr ? decoded_reg_strb.ext_rez : '0;
    assign hwif_out.ext_rez.req_is_wr = decoded_req_is_wr;
    assign hwif_out.ext_rez.wr_data = decoded_wr_data;
    assign hwif_out.ext_rez.wr_biten = decoded_wr_biten;

    assign hwif_out.ext_rea.req = decoded_reg_strb.ext_rea;
    assign hwif_out.ext_rea.req_is_wr = decoded_req_is_wr;
    assign hwif_out.ext_rea.wr_data = decoded_wr_data;
    assign hwif_out.ext_rea.wr_biten = decoded_wr_biten;
    for(genvar i0=0; i0<64; i0++) begin

        assign hwif_out.ext_reg_array[i0].req = !decoded_req_is_wr ? decoded_reg_strb.ext_reg_array[i0] : '0;
        assign hwif_out.ext_reg_array[i0].req_is_wr = decoded_req_is_wr;
    end
    for(genvar i0=0; i0<8; i0++) begin

        assign hwif_out.ext_rea_array[i0].req = decoded_reg_strb.ext_rea_array[i0];
        assign hwif_out.ext_rea_array[i0].req_is_wr = decoded_req_is_wr;
        assign hwif_out.ext_rea_array[i0].wr_data = decoded_wr_data;
        assign hwif_out.ext_rea_array[i0].wr_biten = decoded_wr_biten;
    end

    assign hwif_out.wide_ext_reg.req = decoded_reg_strb.wide_ext_reg;
    assign hwif_out.wide_ext_reg.req_is_wr = decoded_req_is_wr;
    assign hwif_out.wide_ext_reg.wr_data = decoded_wr_data;
    assign hwif_out.wide_ext_reg.wr_biten = decoded_wr_biten;
    for(genvar i0=0; i0<8; i0++) begin

        assign hwif_out.wide_ext_reg_array[i0].req = decoded_reg_strb.wide_ext_reg_array[i0];
        assign hwif_out.wide_ext_reg_array[i0].req_is_wr = decoded_req_is_wr;
        assign hwif_out.wide_ext_reg_array[i0].wr_data = decoded_wr_data;
        assign hwif_out.wide_ext_reg_array[i0].wr_biten = decoded_wr_biten;
    end
    for(genvar i0=0; i0<3; i0++) begin
        for(genvar i1=0; i1<5; i1++) begin

            assign hwif_out.ext_rea_yyyay[i0][i1].req = decoded_reg_strb.ext_rea_yyyay[i0][i1];
            assign hwif_out.ext_rea_yyyay[i0][i1].req_is_wr = decoded_req_is_wr;
            assign hwif_out.ext_rea_yyyay[i0][i1].wr_data = decoded_wr_data;
            assign hwif_out.ext_rea_yyyay[i0][i1].wr_biten = decoded_wr_biten;
        end
    end
    assign hwif_out.rf.req = decoded_reg_strb.rf;
    assign hwif_out.rf.addr = decoded_addr[5:0];
    assign hwif_out.rf.req_is_wr = decoded_req_is_wr;
    assign hwif_out.rf.wr_data = decoded_wr_data;
    assign hwif_out.rf.wr_biten = decoded_wr_biten;
    assign hwif_out.rx.req = decoded_reg_strb.rx;
    assign hwif_out.rx.addr = decoded_addr[5:0];
    assign hwif_out.rx.req_is_wr = decoded_req_is_wr;
    assign hwif_out.rx.wr_data = decoded_wr_data;
    assign hwif_out.rx.wr_biten = decoded_wr_biten;
    assign hwif_out.mm.req = decoded_reg_strb.mm;
    assign hwif_out.mm.addr = decoded_addr[5:0];
    assign hwif_out.mm.req_is_wr = decoded_req_is_wr;
    assign hwif_out.mm.wr_data = decoded_wr_data;
    assign hwif_out.mm.wr_biten = decoded_wr_biten;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    always_comb begin
        automatic logic wr_ack;
        wr_ack = '0;
        wr_ack |= hwif_in.ext_rew.wr_ack;
        wr_ack |= hwif_in.ext_rez.wr_ack;
        wr_ack |= hwif_in.ext_rea.wr_ack;
        for(int i0=0; i0<8; i0++) begin
            wr_ack |= hwif_in.ext_rea_array[i0].wr_ack;
        end
        wr_ack |= hwif_in.wide_ext_reg.wr_ack;
        for(int i0=0; i0<8; i0++) begin
            wr_ack |= hwif_in.wide_ext_reg_array[i0].wr_ack;
        end
        for(int i0=0; i0<3; i0++) begin
            for(int i1=0; i1<5; i1++) begin
                wr_ack |= hwif_in.ext_rea_yyyay[i0][i1].wr_ack;
            end
        end
        wr_ack |= hwif_in.rf.wr_ack;
        wr_ack |= hwif_in.rx.wr_ack;
        wr_ack |= hwif_in.mm.wr_ack;
        external_wr_ack = wr_ack;
    end
    assign cpuif_wr_ack = external_wr_ack | (decoded_req & decoded_req_is_wr & ~decoded_strb_is_external);
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------
    logic readback_external_rd_ack_c;
    always_comb begin
        automatic logic rd_ack;
        rd_ack = '0;
        rd_ack |= hwif_in.ext_reg.rd_ack;
        rd_ack |= hwif_in.ext_ret.rd_ack;
        rd_ack |= hwif_in.ext_rex.rd_ack;
        rd_ack |= hwif_in.ext_rew.rd_ack;
        rd_ack |= hwif_in.ext_rea.rd_ack;
        for(int i0=0; i0<64; i0++) begin
            rd_ack |= hwif_in.ext_reg_array[i0].rd_ack;
        end
        for(int i0=0; i0<8; i0++) begin
            rd_ack |= hwif_in.ext_rea_array[i0].rd_ack;
        end
        rd_ack |= hwif_in.wide_ext_reg.rd_ack;
        for(int i0=0; i0<8; i0++) begin
            rd_ack |= hwif_in.wide_ext_reg_array[i0].rd_ack;
        end
        for(int i0=0; i0<3; i0++) begin
            for(int i1=0; i1<5; i1++) begin
                rd_ack |= hwif_in.ext_rea_yyyay[i0][i1].rd_ack;
            end
        end
        rd_ack |= hwif_in.rf.rd_ack;
        rd_ack |= hwif_in.rx.rd_ack;
        rd_ack |= hwif_in.mm.rd_ack;
        readback_external_rd_ack_c = rd_ack;
    end

    logic readback_external_rd_ack;

    assign readback_external_rd_ack = readback_external_rd_ack_c;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;

    // Assign readback values to a flattened array
    logic [31:0] readback_array[104];
    assign readback_array[0] = hwif_in.ext_reg.rd_ack ? hwif_in.ext_reg.rd_data : '0;
    assign readback_array[1] = hwif_in.ext_ret.rd_ack ? hwif_in.ext_ret.rd_data : '0;
    assign readback_array[2] = hwif_in.ext_rex.rd_ack ? hwif_in.ext_rex.rd_data : '0;
    assign readback_array[3] = hwif_in.ext_rew.rd_ack ? hwif_in.ext_rew.rd_data : '0;
    assign readback_array[4] = hwif_in.ext_rea.rd_ack ? hwif_in.ext_rea.rd_data : '0;
    for(genvar i0=0; i0<64; i0++) begin
        assign readback_array[i0*1 + 5] = hwif_in.ext_reg_array[i0].rd_ack ? hwif_in.ext_reg_array[i0].rd_data : '0;
    end
    for(genvar i0=0; i0<8; i0++) begin
        assign readback_array[i0*1 + 69] = hwif_in.ext_rea_array[i0].rd_ack ? hwif_in.ext_rea_array[i0].rd_data : '0;
    end
    assign readback_array[77] = hwif_in.wide_ext_reg.rd_ack ? hwif_in.wide_ext_reg.rd_data : '0;
    for(genvar i0=0; i0<8; i0++) begin
        assign readback_array[i0*1 + 78] = hwif_in.wide_ext_reg_array[i0].rd_ack ? hwif_in.wide_ext_reg_array[i0].rd_data : '0;
    end
    for(genvar i0=0; i0<3; i0++) begin
        for(genvar i1=0; i1<5; i1++) begin
            assign readback_array[i0*5 + i1*1 + 86] = hwif_in.ext_rea_yyyay[i0][i1].rd_ack ? hwif_in.ext_rea_yyyay[i0][i1].rd_data : '0;
        end
    end
    assign readback_array[101] = hwif_in.rf.rd_ack ? hwif_in.rf.rd_data : '0;
    assign readback_array[102] = hwif_in.rx.rd_ack ? hwif_in.rx.rd_data : '0;
    assign readback_array[103] = hwif_in.mm.rd_ack ? hwif_in.mm.rd_data : '0;

    // Reduce the array
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr & ~decoded_strb_is_external;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<104; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign external_rd_ack = readback_external_rd_ack;
    assign cpuif_rd_ack = readback_done | readback_external_rd_ack;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
