// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package regblock_pkg;

    localparam REGBLOCK_DATA_WIDTH = 8;
    localparam REGBLOCK_MIN_ADDR_WIDTH = 4;
    localparam REGBLOCK_SIZE = 'ha;

    typedef struct {
        logic [7:0] next;
        logic we;
    } top__r1__f__in_t;

    typedef struct {
        top__r1__f__in_t f;
    } top__r1__in_t;

    typedef struct {
        logic [7:0] next;
        logic wel;
    } top__r3__f__in_t;

    typedef struct {
        top__r3__f__in_t f;
    } top__r3__in_t;

    typedef struct {
        logic [7:0] next;
        logic we;
    } top__r5__f__in_t;

    typedef struct {
        top__r5__f__in_t f;
    } top__r5__in_t;

    typedef struct {
        logic [7:0] next;
    } top__r7__f__in_t;

    typedef struct {
        top__r7__f__in_t f;
    } top__r7__in_t;

    typedef struct {
        logic [7:0] next;
        logic we;
    } top__r9__f__in_t;

    typedef struct {
        top__r9__f__in_t f;
    } top__r9__in_t;

    typedef struct {
        top__r1__in_t r1;
        top__r3__in_t r3;
        top__r5__in_t r5;
        top__r7__in_t r7;
        top__r9__in_t r9;
    } regblock__in_t;

    typedef struct {
        logic [7:0] value;
    } top__r1__f__out_t;

    typedef struct {
        top__r1__f__out_t f;
    } top__r1__out_t;

    typedef struct {
        logic [7:0] value;
    } top__r2__f__out_t;

    typedef struct {
        top__r2__f__out_t f;
    } top__r2__out_t;

    typedef struct {
        logic [7:0] value;
    } top__r5__f__out_t;

    typedef struct {
        top__r5__f__out_t f;
    } top__r5__out_t;

    typedef struct {
        logic [7:0] value;
    } top__r6__f__out_t;

    typedef struct {
        top__r6__f__out_t f;
    } top__r6__out_t;

    typedef struct {
        logic [7:0] value;
    } top__r9__f__out_t;

    typedef struct {
        top__r9__f__out_t f;
    } top__r9__out_t;

    typedef struct {
        logic [7:0] value;
    } top__r10__f__out_t;

    typedef struct {
        top__r10__f__out_t f;
    } top__r10__out_t;

    typedef struct {
        top__r1__out_t r1;
        top__r2__out_t r2;
        top__r5__out_t r5;
        top__r6__out_t r6;
        top__r9__out_t r9;
        top__r10__out_t r10;
    } regblock__out_t;
endpackage
