// Generated by PeakRDL-regblock HWIF Wrapper Tool
//  https://github.com/SystemRDL/PeakRDL-regblock
//
// This is a wrapper module that flattens the hwif structs into individual signals

module regblock_wrapper (
        input wire clk,
        input wire rst,
        input wire s_apb_psel,
        input wire s_apb_penable,
        input wire s_apb_pwrite,
        input wire [2:0] s_apb_pprot,
        input wire [3:0] s_apb_paddr,
        input wire [31:0] s_apb_pwdata,
        input wire [3:0] s_apb_pstrb,
        output logic s_apb_pready,
        output logic [31:0] s_apb_prdata,
        output logic s_apb_pslverr,
        input logic hwif_in_STATUS_ready,
        input logic hwif_in_STATUS_error,
        input logic [7:0] hwif_in_STATUS_status,
        input logic [7:0] hwif_in_DATA_value,
        output logic hwif_out_CONTROL_enable,
        output logic [2:0] hwif_out_CONTROL_mode,
        output logic [7:0] hwif_out_DATA_value
    );

    //--------------------------------------------------------------------------
    // Internal hwif struct signals
    //--------------------------------------------------------------------------
    regblock_pkg::regblock__in_t hwif_in;
    regblock_pkg::regblock__out_t hwif_out;

    //--------------------------------------------------------------------------
    // Flatten struct to individual signals
    //--------------------------------------------------------------------------
    assign hwif_in.STATUS.ready.next = hwif_in_STATUS_ready;
    assign hwif_in.STATUS.error.next = hwif_in_STATUS_error;
    assign hwif_in.STATUS.status.next = hwif_in_STATUS_status;
    assign hwif_in.DATA.value.next = hwif_in_DATA_value;

    assign hwif_out_CONTROL_enable = hwif_out.CONTROL.enable.value;
    assign hwif_out_CONTROL_mode = hwif_out.CONTROL.mode.value;
    assign hwif_out_DATA_value = hwif_out.DATA.value.value;

    //--------------------------------------------------------------------------
    // Instantiate the main regblock module
    //--------------------------------------------------------------------------
    regblock i_regblock (
        .clk(clk),
        .rst(rst),
        .s_apb_psel(s_apb_psel),
        .s_apb_penable(s_apb_penable),
        .s_apb_pwrite(s_apb_pwrite),
        .s_apb_pprot(s_apb_pprot),
        .s_apb_paddr(s_apb_paddr),
        .s_apb_pwdata(s_apb_pwdata),
        .s_apb_pstrb(s_apb_pstrb),
        .s_apb_pready(s_apb_pready),
        .s_apb_prdata(s_apb_prdata),
        .s_apb_pslverr(s_apb_pslverr),
        .hwif_in(hwif_in),
        .hwif_out(hwif_out)
    );

endmodule
