// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package regblock_pkg;

    localparam REGBLOCK_DATA_WIDTH = 32;
    localparam REGBLOCK_MIN_ADDR_WIDTH = 3;
    localparam REGBLOCK_SIZE = 'h4;
    localparam N_REGS = 'h1;
    localparam REGWIDTH = 'h20;
    localparam NAME = abcd;

    typedef struct {
        logic [31:0] value;
    } top__reg_t__f__out_t;

    typedef struct {
        top__reg_t__f__out_t f;
    } top__reg_t__out_t;

    typedef struct {
        top__reg_t__out_t regs[1];
    } regblock__out_t;
endpackage
