// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package regblock_pkg;

    localparam REGBLOCK_DATA_WIDTH = 32;
    localparam REGBLOCK_MIN_ADDR_WIDTH = 3;
    localparam REGBLOCK_SIZE = 'h8;

    typedef struct {
        logic incr;
    } top__simple__implied_up__in_t;

    typedef struct {
        logic incr;
    } top__simple__up__in_t;

    typedef struct {
        logic decr;
    } top__simple__down__in_t;

    typedef struct {
        logic incr;
        logic decr;
    } top__simple__updown__in_t;

    typedef struct {
        logic [1:0] incrvalue;
        logic [1:0] decrvalue;
    } top__simple__updown3_decr_3c6a53da_incr_15bc9a96__in_t;

    typedef struct {
        top__simple__implied_up__in_t implied_up;
        top__simple__up__in_t up;
        top__simple__down__in_t down;
        top__simple__updown__in_t updown;
        top__simple__updown3_decr_3c6a53da_incr_15bc9a96__in_t updown3;
    } top__simple__in_t;

    typedef struct {
        top__simple__in_t simple;
    } regblock__in_t;

    typedef struct {
        logic [3:0] value;
        logic overflow;
        logic underflow;
    } top__simple__updown__out_t;

    typedef struct {
        logic value;
    } top__simple__do_count_up__out_t;

    typedef struct {
        logic value;
    } top__simple__do_count_down__out_t;

    typedef struct {
        top__simple__updown__out_t updown;
        top__simple__do_count_up__out_t do_count_up;
        top__simple__do_count_down__out_t do_count_down;
    } top__simple__out_t;

    typedef struct {
        top__simple__out_t simple;
    } regblock__out_t;
endpackage
