// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package regblock_pkg;

    localparam REGBLOCK_DATA_WIDTH = 32;
    localparam REGBLOCK_MIN_ADDR_WIDTH = 4;
    localparam REGBLOCK_SIZE = 'h10;

    typedef struct {
        logic incr;
        logic decr;
    } top__threshold_via_bool__count__in_t;

    typedef struct {
        top__threshold_via_bool__count__in_t count;
    } top__threshold_via_bool__in_t;

    typedef struct {
        logic incr;
        logic decr;
    } top__threshold_via_const__count__in_t;

    typedef struct {
        top__threshold_via_const__count__in_t count;
    } top__threshold_via_const__in_t;

    typedef struct {
        logic incr;
        logic decr;
    } top__threshold_via_ref_count_f52d44fd__count_decrthreshold_406f6bf3_incrthreshold_aa74806a__in_t;

    typedef struct {
        top__threshold_via_ref_count_f52d44fd__count_decrthreshold_406f6bf3_incrthreshold_aa74806a__in_t count;
    } top__threshold_via_ref_count_f52d44fd__in_t;

    typedef struct {
        top__threshold_via_bool__in_t threshold_via_bool;
        top__threshold_via_const__in_t threshold_via_const;
        top__threshold_via_ref_count_f52d44fd__in_t threshold_via_ref;
    } regblock__in_t;

    typedef struct {
        logic [3:0] value;
        logic incrthreshold;
        logic decrthreshold;
    } top__threshold_via_bool__count__out_t;

    typedef struct {
        top__threshold_via_bool__count__out_t count;
    } top__threshold_via_bool__out_t;

    typedef struct {
        logic [3:0] value;
        logic incrthreshold;
        logic decrthreshold;
    } top__threshold_via_const__count__out_t;

    typedef struct {
        top__threshold_via_const__count__out_t count;
    } top__threshold_via_const__out_t;

    typedef struct {
        logic [3:0] value;
        logic incrthreshold;
        logic decrthreshold;
    } top__threshold_via_ref_count_f52d44fd__count_decrthreshold_406f6bf3_incrthreshold_aa74806a__out_t;

    typedef struct {
        top__threshold_via_ref_count_f52d44fd__count_decrthreshold_406f6bf3_incrthreshold_aa74806a__out_t count;
    } top__threshold_via_ref_count_f52d44fd__out_t;

    typedef struct {
        top__threshold_via_bool__out_t threshold_via_bool;
        top__threshold_via_const__out_t threshold_via_const;
        top__threshold_via_ref_count_f52d44fd__out_t threshold_via_ref;
    } regblock__out_t;
endpackage
