/* Generated by Yosys 0.58 (git sha1 157aabb58, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module regblock(clk, rst, s_apb_psel, s_apb_pwrite, s_apb_penable, s_apb_pprot, s_apb_paddr, s_apb_pwdata, s_apb_pstrb, s_apb_pready, s_apb_prdata, s_apb_pslverr, hwif_out_r1_f_q8_8, hwif_in_r1_f_q32_n12, hwif_out_r1_f_sqn8_32, hwif_out_r1_f_sqn6_7, hwif_in_r2_f_signed, hwif_out_r2_f_unsigned, hwif_in_r2_f_no_sign);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input s_apb_psel;
  wire s_apb_psel;
  input s_apb_pwrite;
  wire s_apb_pwrite;
  input s_apb_penable;
  wire s_apb_penable;
  input [2:0] s_apb_pprot;
  wire [2:0] s_apb_pprot;
  input [3:0] s_apb_paddr;
  wire [3:0] s_apb_paddr;
  input [63:0] s_apb_pwdata;
  wire [63:0] s_apb_pwdata;
  input [7:0] s_apb_pstrb;
  wire [7:0] s_apb_pstrb;
  output s_apb_pready;
  wire s_apb_pready;
  output [63:0] s_apb_prdata;
  wire [63:0] s_apb_prdata;
  output s_apb_pslverr;
  wire s_apb_pslverr;
  output [15:0] hwif_out_r1_f_q8_8;
  wire [15:0] hwif_out_r1_f_q8_8;
  input [19:0] hwif_in_r1_f_q32_n12;
  wire [19:0] hwif_in_r1_f_q32_n12;
  output [23:0] hwif_out_r1_f_sqn8_32;
  wire [23:0] hwif_out_r1_f_sqn8_32;
  output [0:0] hwif_out_r1_f_sqn6_7;
  wire [0:0] hwif_out_r1_f_sqn6_7;
  input [15:0] hwif_in_r2_f_signed;
  wire [15:0] hwif_in_r2_f_signed;
  output [15:0] hwif_out_r2_f_unsigned;
  wire [15:0] hwif_out_r2_f_unsigned;
  input [15:0] hwif_in_r2_f_no_sign;
  wire [15:0] hwif_in_r2_f_no_sign;
  wire [15:0] _000_;
  wire [15:0] _001_;
  wire [23:0] _002_;
  wire [23:0] _003_;
  wire _004_;
  wire _005_;
  wire [15:0] _006_;
  wire [15:0] _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire [15:0] _015_;
  wire [23:0] _016_;
  wire [15:0] _017_;
  wire [15:0] _018_;
  wire [23:0] _019_;
  wire _020_;
  wire [15:0] _021_;
  wire _022_;
  wire _023_;
  wire [3:0] cpuif_addr;
  wire cpuif_rd_ack;
  wire [63:0] cpuif_rd_data;
  wire cpuif_rd_err;
  reg cpuif_req;
  reg cpuif_req_is_wr;
  wire cpuif_req_masked;
  wire cpuif_req_stall_rd;
  wire cpuif_req_stall_wr;
  wire cpuif_wr_ack;
  wire [63:0] cpuif_wr_biten;
  wire [63:0] cpuif_wr_data;
  wire cpuif_wr_err;
  wire [0:0] decoded_reg_strb_r1;
  wire [0:0] decoded_reg_strb_r2;
  wire decoded_req;
  wire decoded_req_is_wr;
  wire [63:0] decoded_wr_biten;
  wire [63:0] decoded_wr_data;
  wire field_combo_r1_f_q8_8_load_next;
  wire field_combo_r1_f_sqn6_7_load_next;
  wire field_combo_r1_f_sqn8_32_load_next;
  wire field_combo_r2_f_unsigned_load_next;
  reg [15:0] field_storage_r1_f_q8_8_value;
  reg [0:0] field_storage_r1_f_sqn6_7_value;
  reg [23:0] field_storage_r1_f_sqn8_32_value;
  reg [15:0] field_storage_r2_f_unsigned_value;
  reg is_active;
  wire [63:0] \readback_array[0] ;
  wire [63:0] \readback_array[1] ;
  wire [63:0] readback_data;
  wire readback_done;
  wire readback_err;
  wire readback_external_rd_ack;
  reg \cpuif_wr_data_reg[2] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[2]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[2]  <= s_apb_pwdata[2];
  assign cpuif_wr_data[2] = \cpuif_wr_data_reg[2] ;
  reg \cpuif_wr_data_reg[3] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[3]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[3]  <= s_apb_pwdata[3];
  assign cpuif_wr_data[3] = \cpuif_wr_data_reg[3] ;
  reg \cpuif_wr_data_reg[4] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[4]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[4]  <= s_apb_pwdata[4];
  assign cpuif_wr_data[4] = \cpuif_wr_data_reg[4] ;
  reg \cpuif_wr_data_reg[5] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[5]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[5]  <= s_apb_pwdata[5];
  assign cpuif_wr_data[5] = \cpuif_wr_data_reg[5] ;
  reg \cpuif_wr_data_reg[6] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[6]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[6]  <= s_apb_pwdata[6];
  assign cpuif_wr_data[6] = \cpuif_wr_data_reg[6] ;
  reg \cpuif_wr_data_reg[7] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[7]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[7]  <= s_apb_pwdata[7];
  assign cpuif_wr_data[7] = \cpuif_wr_data_reg[7] ;
  reg \cpuif_wr_data_reg[8] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[8]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[8]  <= s_apb_pwdata[8];
  assign cpuif_wr_data[8] = \cpuif_wr_data_reg[8] ;
  reg \cpuif_wr_data_reg[9] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[9]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[9]  <= s_apb_pwdata[9];
  assign cpuif_wr_data[9] = \cpuif_wr_data_reg[9] ;
  reg \cpuif_wr_data_reg[10] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[10]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[10]  <= s_apb_pwdata[10];
  assign cpuif_wr_data[10] = \cpuif_wr_data_reg[10] ;
  reg \cpuif_wr_data_reg[11] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[11]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[11]  <= s_apb_pwdata[11];
  assign cpuif_wr_data[11] = \cpuif_wr_data_reg[11] ;
  reg \cpuif_wr_data_reg[12] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[12]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[12]  <= s_apb_pwdata[12];
  assign cpuif_wr_data[12] = \cpuif_wr_data_reg[12] ;
  reg \cpuif_wr_data_reg[13] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[13]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[13]  <= s_apb_pwdata[13];
  assign cpuif_wr_data[13] = \cpuif_wr_data_reg[13] ;
  reg \cpuif_wr_data_reg[14] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[14]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[14]  <= s_apb_pwdata[14];
  assign cpuif_wr_data[14] = \cpuif_wr_data_reg[14] ;
  reg \cpuif_wr_data_reg[15] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[15]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[15]  <= s_apb_pwdata[15];
  assign cpuif_wr_data[15] = \cpuif_wr_data_reg[15] ;
  reg \cpuif_wr_data_reg[16] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[16]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[16]  <= s_apb_pwdata[16];
  assign cpuif_wr_data[16] = \cpuif_wr_data_reg[16] ;
  reg \cpuif_wr_data_reg[17] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[17]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[17]  <= s_apb_pwdata[17];
  assign cpuif_wr_data[17] = \cpuif_wr_data_reg[17] ;
  reg \cpuif_wr_data_reg[18] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[18]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[18]  <= s_apb_pwdata[18];
  assign cpuif_wr_data[18] = \cpuif_wr_data_reg[18] ;
  reg \cpuif_wr_data_reg[19] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[19]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[19]  <= s_apb_pwdata[19];
  assign cpuif_wr_data[19] = \cpuif_wr_data_reg[19] ;
  reg \cpuif_wr_data_reg[20] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[20]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[20]  <= s_apb_pwdata[20];
  assign cpuif_wr_data[20] = \cpuif_wr_data_reg[20] ;
  reg \cpuif_wr_data_reg[21] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[21]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[21]  <= s_apb_pwdata[21];
  assign cpuif_wr_data[21] = \cpuif_wr_data_reg[21] ;
  reg \cpuif_wr_data_reg[22] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[22]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[22]  <= s_apb_pwdata[22];
  assign cpuif_wr_data[22] = \cpuif_wr_data_reg[22] ;
  reg \cpuif_wr_data_reg[23] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[23]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[23]  <= s_apb_pwdata[23];
  assign cpuif_wr_data[23] = \cpuif_wr_data_reg[23] ;
  reg \cpuif_wr_data_reg[24] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[24]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[24]  <= s_apb_pwdata[24];
  assign cpuif_wr_data[24] = \cpuif_wr_data_reg[24] ;
  reg \cpuif_wr_data_reg[25] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[25]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[25]  <= s_apb_pwdata[25];
  assign cpuif_wr_data[25] = \cpuif_wr_data_reg[25] ;
  reg \cpuif_wr_data_reg[26] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[26]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[26]  <= s_apb_pwdata[26];
  assign cpuif_wr_data[26] = \cpuif_wr_data_reg[26] ;
  reg \cpuif_wr_data_reg[27] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[27]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[27]  <= s_apb_pwdata[27];
  assign cpuif_wr_data[27] = \cpuif_wr_data_reg[27] ;
  reg \cpuif_wr_data_reg[28] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[28]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[28]  <= s_apb_pwdata[28];
  assign cpuif_wr_data[28] = \cpuif_wr_data_reg[28] ;
  reg \cpuif_wr_data_reg[29] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[29]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[29]  <= s_apb_pwdata[29];
  assign cpuif_wr_data[29] = \cpuif_wr_data_reg[29] ;
  reg \cpuif_wr_data_reg[30] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[30]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[30]  <= s_apb_pwdata[30];
  assign cpuif_wr_data[30] = \cpuif_wr_data_reg[30] ;
  reg \cpuif_wr_data_reg[31] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[31]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[31]  <= s_apb_pwdata[31];
  assign cpuif_wr_data[31] = \cpuif_wr_data_reg[31] ;
  reg \cpuif_wr_data_reg[36] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[36]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[36]  <= s_apb_pwdata[36];
  assign cpuif_wr_data[36] = \cpuif_wr_data_reg[36] ;
  reg \cpuif_wr_data_reg[37] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[37]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[37]  <= s_apb_pwdata[37];
  assign cpuif_wr_data[37] = \cpuif_wr_data_reg[37] ;
  reg \cpuif_wr_data_reg[38] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[38]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[38]  <= s_apb_pwdata[38];
  assign cpuif_wr_data[38] = \cpuif_wr_data_reg[38] ;
  reg \cpuif_wr_data_reg[39] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[39]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[39]  <= s_apb_pwdata[39];
  assign cpuif_wr_data[39] = \cpuif_wr_data_reg[39] ;
  reg \cpuif_wr_data_reg[40] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[40]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[40]  <= s_apb_pwdata[40];
  assign cpuif_wr_data[40] = \cpuif_wr_data_reg[40] ;
  reg \cpuif_wr_data_reg[41] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[41]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[41]  <= s_apb_pwdata[41];
  assign cpuif_wr_data[41] = \cpuif_wr_data_reg[41] ;
  reg \cpuif_wr_data_reg[42] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[42]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[42]  <= s_apb_pwdata[42];
  assign cpuif_wr_data[42] = \cpuif_wr_data_reg[42] ;
  reg \cpuif_wr_data_reg[43] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[43]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[43]  <= s_apb_pwdata[43];
  assign cpuif_wr_data[43] = \cpuif_wr_data_reg[43] ;
  reg \cpuif_wr_data_reg[44] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[44]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[44]  <= s_apb_pwdata[44];
  assign cpuif_wr_data[44] = \cpuif_wr_data_reg[44] ;
  reg \cpuif_wr_data_reg[45] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[45]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[45]  <= s_apb_pwdata[45];
  assign cpuif_wr_data[45] = \cpuif_wr_data_reg[45] ;
  reg \cpuif_wr_data_reg[46] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[46]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[46]  <= s_apb_pwdata[46];
  assign cpuif_wr_data[46] = \cpuif_wr_data_reg[46] ;
  reg \cpuif_wr_data_reg[47] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[47]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[47]  <= s_apb_pwdata[47];
  assign cpuif_wr_data[47] = \cpuif_wr_data_reg[47] ;
  reg \cpuif_wr_data_reg[48] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[48]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[48]  <= s_apb_pwdata[48];
  assign cpuif_wr_data[48] = \cpuif_wr_data_reg[48] ;
  reg \cpuif_wr_data_reg[49] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[49]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[49]  <= s_apb_pwdata[49];
  assign cpuif_wr_data[49] = \cpuif_wr_data_reg[49] ;
  reg \cpuif_wr_data_reg[50] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[50]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[50]  <= s_apb_pwdata[50];
  assign cpuif_wr_data[50] = \cpuif_wr_data_reg[50] ;
  reg \cpuif_wr_data_reg[51] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[51]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[51]  <= s_apb_pwdata[51];
  assign cpuif_wr_data[51] = \cpuif_wr_data_reg[51] ;
  reg \cpuif_wr_data_reg[52] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[52]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[52]  <= s_apb_pwdata[52];
  assign cpuif_wr_data[52] = \cpuif_wr_data_reg[52] ;
  reg \cpuif_wr_data_reg[53] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[53]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[53]  <= s_apb_pwdata[53];
  assign cpuif_wr_data[53] = \cpuif_wr_data_reg[53] ;
  reg \cpuif_wr_data_reg[54] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[54]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[54]  <= s_apb_pwdata[54];
  assign cpuif_wr_data[54] = \cpuif_wr_data_reg[54] ;
  reg \cpuif_wr_data_reg[55] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[55]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[55]  <= s_apb_pwdata[55];
  assign cpuif_wr_data[55] = \cpuif_wr_data_reg[55] ;
  reg \cpuif_wr_data_reg[56] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[56]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[56]  <= s_apb_pwdata[56];
  assign cpuif_wr_data[56] = \cpuif_wr_data_reg[56] ;
  reg \cpuif_wr_data_reg[57] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[57]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[57]  <= s_apb_pwdata[57];
  assign cpuif_wr_data[57] = \cpuif_wr_data_reg[57] ;
  reg \cpuif_wr_data_reg[58] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[58]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[58]  <= s_apb_pwdata[58];
  assign cpuif_wr_data[58] = \cpuif_wr_data_reg[58] ;
  reg \cpuif_wr_data_reg[59] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[59]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[59]  <= s_apb_pwdata[59];
  assign cpuif_wr_data[59] = \cpuif_wr_data_reg[59] ;
  reg \cpuif_wr_data_reg[60] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[60]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[60]  <= s_apb_pwdata[60];
  assign cpuif_wr_data[60] = \cpuif_wr_data_reg[60] ;
  reg \cpuif_wr_biten_reg[5] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_biten_reg[5]  <= 1'h0;
    else if (_008_) \cpuif_wr_biten_reg[5]  <= s_apb_pstrb[0];
  assign cpuif_wr_biten[5] = \cpuif_wr_biten_reg[5] ;
  reg \cpuif_addr_reg[3] ;
  always @(posedge clk)
    if (rst) \cpuif_addr_reg[3]  <= 1'h0;
    else if (_008_) \cpuif_addr_reg[3]  <= s_apb_paddr[3];
  assign cpuif_addr[3] = \cpuif_addr_reg[3] ;
  always @(posedge clk)
    if (rst) is_active <= 1'h0;
    else is_active <= _023_;
  always @(posedge clk)
    if (rst) field_storage_r1_f_sqn8_32_value[0] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_sqn8_32_value[0] <= _019_[0];
  always @(posedge clk)
    if (rst) field_storage_r1_f_sqn8_32_value[1] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_sqn8_32_value[1] <= _019_[1];
  always @(posedge clk)
    if (rst) field_storage_r1_f_sqn8_32_value[2] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_sqn8_32_value[2] <= _019_[2];
  always @(posedge clk)
    if (rst) field_storage_r1_f_sqn8_32_value[3] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_sqn8_32_value[3] <= _019_[3];
  always @(posedge clk)
    if (rst) field_storage_r1_f_sqn8_32_value[4] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_sqn8_32_value[4] <= _019_[4];
  always @(posedge clk)
    if (rst) field_storage_r1_f_sqn8_32_value[5] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_sqn8_32_value[5] <= _019_[5];
  always @(posedge clk)
    if (rst) field_storage_r1_f_sqn8_32_value[6] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_sqn8_32_value[6] <= _019_[6];
  always @(posedge clk)
    if (rst) field_storage_r1_f_sqn8_32_value[7] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_sqn8_32_value[7] <= _019_[7];
  always @(posedge clk)
    if (rst) field_storage_r1_f_sqn8_32_value[8] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_sqn8_32_value[8] <= _019_[8];
  always @(posedge clk)
    if (rst) field_storage_r1_f_sqn8_32_value[9] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_sqn8_32_value[9] <= _019_[9];
  always @(posedge clk)
    if (rst) field_storage_r1_f_sqn8_32_value[10] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_sqn8_32_value[10] <= _019_[10];
  always @(posedge clk)
    if (rst) field_storage_r1_f_sqn8_32_value[11] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_sqn8_32_value[11] <= _019_[11];
  always @(posedge clk)
    if (rst) field_storage_r1_f_sqn8_32_value[12] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_sqn8_32_value[12] <= _019_[12];
  always @(posedge clk)
    if (rst) field_storage_r1_f_sqn8_32_value[13] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_sqn8_32_value[13] <= _019_[13];
  always @(posedge clk)
    if (rst) field_storage_r1_f_sqn8_32_value[14] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_sqn8_32_value[14] <= _019_[14];
  always @(posedge clk)
    if (rst) field_storage_r1_f_sqn8_32_value[15] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_sqn8_32_value[15] <= _019_[15];
  always @(posedge clk)
    if (rst) field_storage_r1_f_sqn8_32_value[16] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_sqn8_32_value[16] <= _019_[16];
  always @(posedge clk)
    if (rst) field_storage_r1_f_sqn8_32_value[17] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_sqn8_32_value[17] <= _019_[17];
  always @(posedge clk)
    if (rst) field_storage_r1_f_sqn8_32_value[18] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_sqn8_32_value[18] <= _019_[18];
  always @(posedge clk)
    if (rst) field_storage_r1_f_sqn8_32_value[19] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_sqn8_32_value[19] <= _019_[19];
  always @(posedge clk)
    if (rst) field_storage_r1_f_sqn8_32_value[20] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_sqn8_32_value[20] <= _019_[20];
  always @(posedge clk)
    if (rst) field_storage_r1_f_sqn8_32_value[21] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_sqn8_32_value[21] <= _019_[21];
  always @(posedge clk)
    if (rst) field_storage_r1_f_sqn8_32_value[22] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_sqn8_32_value[22] <= _019_[22];
  always @(posedge clk)
    if (rst) field_storage_r1_f_sqn8_32_value[23] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_sqn8_32_value[23] <= _019_[23];
  reg \cpuif_wr_biten_reg[46] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_biten_reg[46]  <= 1'h0;
    else if (_008_) \cpuif_wr_biten_reg[46]  <= s_apb_pstrb[5];
  assign cpuif_wr_biten[46] = \cpuif_wr_biten_reg[46] ;
  reg \cpuif_wr_biten_reg[38] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_biten_reg[38]  <= 1'h0;
    else if (_008_) \cpuif_wr_biten_reg[38]  <= s_apb_pstrb[4];
  assign cpuif_wr_biten[38] = \cpuif_wr_biten_reg[38] ;
  reg \cpuif_wr_biten_reg[30] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_biten_reg[30]  <= 1'h0;
    else if (_008_) \cpuif_wr_biten_reg[30]  <= s_apb_pstrb[3];
  assign cpuif_wr_biten[30] = \cpuif_wr_biten_reg[30] ;
  reg \cpuif_wr_biten_reg[22] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_biten_reg[22]  <= 1'h0;
    else if (_008_) \cpuif_wr_biten_reg[22]  <= s_apb_pstrb[2];
  assign cpuif_wr_biten[22] = \cpuif_wr_biten_reg[22] ;
  reg \cpuif_wr_biten_reg[14] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_biten_reg[14]  <= 1'h0;
    else if (_008_) \cpuif_wr_biten_reg[14]  <= s_apb_pstrb[1];
  assign cpuif_wr_biten[14] = \cpuif_wr_biten_reg[14] ;
  reg \cpuif_wr_biten_reg[62] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_biten_reg[62]  <= 1'h0;
    else if (_008_) \cpuif_wr_biten_reg[62]  <= s_apb_pstrb[7];
  assign cpuif_wr_biten[62] = \cpuif_wr_biten_reg[62] ;
  reg \cpuif_wr_biten_reg[54] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_biten_reg[54]  <= 1'h0;
    else if (_008_) \cpuif_wr_biten_reg[54]  <= s_apb_pstrb[6];
  assign cpuif_wr_biten[54] = \cpuif_wr_biten_reg[54] ;
  always @(posedge clk)
    if (rst) field_storage_r1_f_q8_8_value[0] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_q8_8_value[0] <= _018_[0];
  always @(posedge clk)
    if (rst) field_storage_r1_f_q8_8_value[1] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_q8_8_value[1] <= _018_[1];
  always @(posedge clk)
    if (rst) field_storage_r1_f_q8_8_value[2] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_q8_8_value[2] <= _018_[2];
  always @(posedge clk)
    if (rst) field_storage_r1_f_q8_8_value[3] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_q8_8_value[3] <= _018_[3];
  always @(posedge clk)
    if (rst) field_storage_r1_f_q8_8_value[4] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_q8_8_value[4] <= _018_[4];
  always @(posedge clk)
    if (rst) field_storage_r1_f_q8_8_value[5] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_q8_8_value[5] <= _018_[5];
  always @(posedge clk)
    if (rst) field_storage_r1_f_q8_8_value[6] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_q8_8_value[6] <= _018_[6];
  always @(posedge clk)
    if (rst) field_storage_r1_f_q8_8_value[7] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_q8_8_value[7] <= _018_[7];
  always @(posedge clk)
    if (rst) field_storage_r1_f_q8_8_value[8] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_q8_8_value[8] <= _018_[8];
  always @(posedge clk)
    if (rst) field_storage_r1_f_q8_8_value[9] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_q8_8_value[9] <= _018_[9];
  always @(posedge clk)
    if (rst) field_storage_r1_f_q8_8_value[10] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_q8_8_value[10] <= _018_[10];
  always @(posedge clk)
    if (rst) field_storage_r1_f_q8_8_value[11] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_q8_8_value[11] <= _018_[11];
  always @(posedge clk)
    if (rst) field_storage_r1_f_q8_8_value[12] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_q8_8_value[12] <= _018_[12];
  always @(posedge clk)
    if (rst) field_storage_r1_f_q8_8_value[13] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_q8_8_value[13] <= _018_[13];
  always @(posedge clk)
    if (rst) field_storage_r1_f_q8_8_value[14] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_q8_8_value[14] <= _018_[14];
  always @(posedge clk)
    if (rst) field_storage_r1_f_q8_8_value[15] <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_q8_8_value[15] <= _018_[15];
  always @(posedge clk)
    if (rst) field_storage_r2_f_unsigned_value[0] <= 1'h0;
    else if (field_combo_r2_f_unsigned_load_next) field_storage_r2_f_unsigned_value[0] <= _021_[0];
  always @(posedge clk)
    if (rst) field_storage_r2_f_unsigned_value[1] <= 1'h0;
    else if (field_combo_r2_f_unsigned_load_next) field_storage_r2_f_unsigned_value[1] <= _021_[1];
  always @(posedge clk)
    if (rst) field_storage_r2_f_unsigned_value[2] <= 1'h0;
    else if (field_combo_r2_f_unsigned_load_next) field_storage_r2_f_unsigned_value[2] <= _021_[2];
  always @(posedge clk)
    if (rst) field_storage_r2_f_unsigned_value[3] <= 1'h0;
    else if (field_combo_r2_f_unsigned_load_next) field_storage_r2_f_unsigned_value[3] <= _021_[3];
  always @(posedge clk)
    if (rst) field_storage_r2_f_unsigned_value[4] <= 1'h0;
    else if (field_combo_r2_f_unsigned_load_next) field_storage_r2_f_unsigned_value[4] <= _021_[4];
  always @(posedge clk)
    if (rst) field_storage_r2_f_unsigned_value[5] <= 1'h0;
    else if (field_combo_r2_f_unsigned_load_next) field_storage_r2_f_unsigned_value[5] <= _021_[5];
  always @(posedge clk)
    if (rst) field_storage_r2_f_unsigned_value[6] <= 1'h0;
    else if (field_combo_r2_f_unsigned_load_next) field_storage_r2_f_unsigned_value[6] <= _021_[6];
  always @(posedge clk)
    if (rst) field_storage_r2_f_unsigned_value[7] <= 1'h0;
    else if (field_combo_r2_f_unsigned_load_next) field_storage_r2_f_unsigned_value[7] <= _021_[7];
  always @(posedge clk)
    if (rst) field_storage_r2_f_unsigned_value[8] <= 1'h0;
    else if (field_combo_r2_f_unsigned_load_next) field_storage_r2_f_unsigned_value[8] <= _021_[8];
  always @(posedge clk)
    if (rst) field_storage_r2_f_unsigned_value[9] <= 1'h0;
    else if (field_combo_r2_f_unsigned_load_next) field_storage_r2_f_unsigned_value[9] <= _021_[9];
  always @(posedge clk)
    if (rst) field_storage_r2_f_unsigned_value[10] <= 1'h0;
    else if (field_combo_r2_f_unsigned_load_next) field_storage_r2_f_unsigned_value[10] <= _021_[10];
  always @(posedge clk)
    if (rst) field_storage_r2_f_unsigned_value[11] <= 1'h0;
    else if (field_combo_r2_f_unsigned_load_next) field_storage_r2_f_unsigned_value[11] <= _021_[11];
  always @(posedge clk)
    if (rst) field_storage_r2_f_unsigned_value[12] <= 1'h0;
    else if (field_combo_r2_f_unsigned_load_next) field_storage_r2_f_unsigned_value[12] <= _021_[12];
  always @(posedge clk)
    if (rst) field_storage_r2_f_unsigned_value[13] <= 1'h0;
    else if (field_combo_r2_f_unsigned_load_next) field_storage_r2_f_unsigned_value[13] <= _021_[13];
  always @(posedge clk)
    if (rst) field_storage_r2_f_unsigned_value[14] <= 1'h0;
    else if (field_combo_r2_f_unsigned_load_next) field_storage_r2_f_unsigned_value[14] <= _021_[14];
  always @(posedge clk)
    if (rst) field_storage_r2_f_unsigned_value[15] <= 1'h0;
    else if (field_combo_r2_f_unsigned_load_next) field_storage_r2_f_unsigned_value[15] <= _021_[15];
  always @(posedge clk)
    if (rst) field_storage_r1_f_sqn6_7_value <= 1'h0;
    else if (field_combo_r1_f_q8_8_load_next) field_storage_r1_f_sqn6_7_value <= _020_;
  always @(posedge clk)
    if (_009_) cpuif_req <= 1'h0;
    else if (s_apb_psel) cpuif_req <= 1'h1;
  always @(posedge clk)
    if (rst) cpuif_req_is_wr <= 1'h0;
    else if (_008_) cpuif_req_is_wr <= s_apb_pwrite;
  reg \cpuif_wr_data_reg[0] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[0]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[0]  <= s_apb_pwdata[0];
  assign cpuif_wr_data[0] = \cpuif_wr_data_reg[0] ;
  reg \cpuif_wr_data_reg[1] ;
  always @(posedge clk)
    if (rst) \cpuif_wr_data_reg[1]  <= 1'h0;
    else if (_008_) \cpuif_wr_data_reg[1]  <= s_apb_pwdata[1];
  assign cpuif_wr_data[1] = \cpuif_wr_data_reg[1] ;
  assign decoded_reg_strb_r1 = cpuif_req & _011_;
  assign decoded_reg_strb_r2 = cpuif_req & cpuif_addr[3];
  assign _000_[0] = field_storage_r1_f_q8_8_value[0] & _015_[7];
  assign _000_[1] = field_storage_r1_f_q8_8_value[1] & _015_[7];
  assign _000_[2] = field_storage_r1_f_q8_8_value[2] & _015_[7];
  assign _000_[3] = field_storage_r1_f_q8_8_value[3] & _015_[7];
  assign _000_[4] = field_storage_r1_f_q8_8_value[4] & _015_[7];
  assign _000_[5] = field_storage_r1_f_q8_8_value[5] & _015_[7];
  assign _000_[6] = field_storage_r1_f_q8_8_value[6] & _015_[7];
  assign _000_[7] = field_storage_r1_f_q8_8_value[7] & _015_[7];
  assign _000_[8] = field_storage_r1_f_q8_8_value[8] & _015_[15];
  assign _000_[9] = field_storage_r1_f_q8_8_value[9] & _015_[15];
  assign _000_[10] = field_storage_r1_f_q8_8_value[10] & _015_[15];
  assign _000_[11] = field_storage_r1_f_q8_8_value[11] & _015_[15];
  assign _000_[12] = field_storage_r1_f_q8_8_value[12] & _015_[15];
  assign _000_[13] = field_storage_r1_f_q8_8_value[13] & _015_[15];
  assign _000_[14] = field_storage_r1_f_q8_8_value[14] & _015_[15];
  assign _000_[15] = field_storage_r1_f_q8_8_value[15] & _015_[15];
  assign _001_[0] = cpuif_wr_data[0] & cpuif_wr_biten[5];
  assign _001_[1] = cpuif_wr_data[1] & cpuif_wr_biten[5];
  assign _001_[2] = cpuif_wr_data[2] & cpuif_wr_biten[5];
  assign _001_[3] = cpuif_wr_data[3] & cpuif_wr_biten[5];
  assign _001_[4] = cpuif_wr_data[4] & cpuif_wr_biten[5];
  assign _001_[5] = cpuif_wr_data[5] & cpuif_wr_biten[5];
  assign _001_[6] = cpuif_wr_data[6] & cpuif_wr_biten[5];
  assign _001_[7] = cpuif_wr_data[7] & cpuif_wr_biten[5];
  assign _001_[8] = cpuif_wr_data[8] & cpuif_wr_biten[14];
  assign _001_[9] = cpuif_wr_data[9] & cpuif_wr_biten[14];
  assign _001_[10] = cpuif_wr_data[10] & cpuif_wr_biten[14];
  assign _001_[11] = cpuif_wr_data[11] & cpuif_wr_biten[14];
  assign _001_[12] = cpuif_wr_data[12] & cpuif_wr_biten[14];
  assign _001_[13] = cpuif_wr_data[13] & cpuif_wr_biten[14];
  assign _001_[14] = cpuif_wr_data[14] & cpuif_wr_biten[14];
  assign _001_[15] = cpuif_wr_data[15] & cpuif_wr_biten[14];
  assign _018_[0] = _000_[0] | _001_[0];
  assign _018_[1] = _000_[1] | _001_[1];
  assign _018_[2] = _000_[2] | _001_[2];
  assign _018_[3] = _000_[3] | _001_[3];
  assign _018_[4] = _000_[4] | _001_[4];
  assign _018_[5] = _000_[5] | _001_[5];
  assign _018_[6] = _000_[6] | _001_[6];
  assign _018_[7] = _000_[7] | _001_[7];
  assign _018_[8] = _000_[8] | _001_[8];
  assign _018_[9] = _000_[9] | _001_[9];
  assign _018_[10] = _000_[10] | _001_[10];
  assign _018_[11] = _000_[11] | _001_[11];
  assign _018_[12] = _000_[12] | _001_[12];
  assign _018_[13] = _000_[13] | _001_[13];
  assign _018_[14] = _000_[14] | _001_[14];
  assign _018_[15] = _000_[15] | _001_[15];
  assign _002_[0] = field_storage_r1_f_sqn8_32_value[0] & _016_[3];
  assign _002_[1] = field_storage_r1_f_sqn8_32_value[1] & _016_[3];
  assign _002_[2] = field_storage_r1_f_sqn8_32_value[2] & _016_[3];
  assign _002_[3] = field_storage_r1_f_sqn8_32_value[3] & _016_[3];
  assign _002_[4] = field_storage_r1_f_sqn8_32_value[4] & _016_[11];
  assign _002_[5] = field_storage_r1_f_sqn8_32_value[5] & _016_[11];
  assign _002_[6] = field_storage_r1_f_sqn8_32_value[6] & _016_[11];
  assign _002_[7] = field_storage_r1_f_sqn8_32_value[7] & _016_[11];
  assign _002_[8] = field_storage_r1_f_sqn8_32_value[8] & _016_[11];
  assign _002_[9] = field_storage_r1_f_sqn8_32_value[9] & _016_[11];
  assign _002_[10] = field_storage_r1_f_sqn8_32_value[10] & _016_[11];
  assign _002_[11] = field_storage_r1_f_sqn8_32_value[11] & _016_[11];
  assign _002_[12] = field_storage_r1_f_sqn8_32_value[12] & _016_[19];
  assign _002_[13] = field_storage_r1_f_sqn8_32_value[13] & _016_[19];
  assign _002_[14] = field_storage_r1_f_sqn8_32_value[14] & _016_[19];
  assign _002_[15] = field_storage_r1_f_sqn8_32_value[15] & _016_[19];
  assign _002_[16] = field_storage_r1_f_sqn8_32_value[16] & _016_[19];
  assign _002_[17] = field_storage_r1_f_sqn8_32_value[17] & _016_[19];
  assign _002_[18] = field_storage_r1_f_sqn8_32_value[18] & _016_[19];
  assign _002_[19] = field_storage_r1_f_sqn8_32_value[19] & _016_[19];
  assign _002_[20] = field_storage_r1_f_sqn8_32_value[20] & _016_[23];
  assign _002_[21] = field_storage_r1_f_sqn8_32_value[21] & _016_[23];
  assign _002_[22] = field_storage_r1_f_sqn8_32_value[22] & _016_[23];
  assign _002_[23] = field_storage_r1_f_sqn8_32_value[23] & _016_[23];
  assign _003_[0] = cpuif_wr_data[36] & cpuif_wr_biten[38];
  assign _003_[1] = cpuif_wr_data[37] & cpuif_wr_biten[38];
  assign _003_[2] = cpuif_wr_data[38] & cpuif_wr_biten[38];
  assign _003_[3] = cpuif_wr_data[39] & cpuif_wr_biten[38];
  assign _003_[4] = cpuif_wr_data[40] & cpuif_wr_biten[46];
  assign _003_[5] = cpuif_wr_data[41] & cpuif_wr_biten[46];
  assign _003_[6] = cpuif_wr_data[42] & cpuif_wr_biten[46];
  assign _003_[7] = cpuif_wr_data[43] & cpuif_wr_biten[46];
  assign _003_[8] = cpuif_wr_data[44] & cpuif_wr_biten[46];
  assign _003_[9] = cpuif_wr_data[45] & cpuif_wr_biten[46];
  assign _003_[10] = cpuif_wr_data[46] & cpuif_wr_biten[46];
  assign _003_[11] = cpuif_wr_data[47] & cpuif_wr_biten[46];
  assign _003_[12] = cpuif_wr_data[48] & cpuif_wr_biten[54];
  assign _003_[13] = cpuif_wr_data[49] & cpuif_wr_biten[54];
  assign _003_[14] = cpuif_wr_data[50] & cpuif_wr_biten[54];
  assign _003_[15] = cpuif_wr_data[51] & cpuif_wr_biten[54];
  assign _003_[16] = cpuif_wr_data[52] & cpuif_wr_biten[54];
  assign _003_[17] = cpuif_wr_data[53] & cpuif_wr_biten[54];
  assign _003_[18] = cpuif_wr_data[54] & cpuif_wr_biten[54];
  assign _003_[19] = cpuif_wr_data[55] & cpuif_wr_biten[54];
  assign _003_[20] = cpuif_wr_data[56] & cpuif_wr_biten[62];
  assign _003_[21] = cpuif_wr_data[57] & cpuif_wr_biten[62];
  assign _003_[22] = cpuif_wr_data[58] & cpuif_wr_biten[62];
  assign _003_[23] = cpuif_wr_data[59] & cpuif_wr_biten[62];
  assign _019_[0] = _002_[0] | _003_[0];
  assign _019_[1] = _002_[1] | _003_[1];
  assign _019_[2] = _002_[2] | _003_[2];
  assign _019_[3] = _002_[3] | _003_[3];
  assign _019_[4] = _002_[4] | _003_[4];
  assign _019_[5] = _002_[5] | _003_[5];
  assign _019_[6] = _002_[6] | _003_[6];
  assign _019_[7] = _002_[7] | _003_[7];
  assign _019_[8] = _002_[8] | _003_[8];
  assign _019_[9] = _002_[9] | _003_[9];
  assign _019_[10] = _002_[10] | _003_[10];
  assign _019_[11] = _002_[11] | _003_[11];
  assign _019_[12] = _002_[12] | _003_[12];
  assign _019_[13] = _002_[13] | _003_[13];
  assign _019_[14] = _002_[14] | _003_[14];
  assign _019_[15] = _002_[15] | _003_[15];
  assign _019_[16] = _002_[16] | _003_[16];
  assign _019_[17] = _002_[17] | _003_[17];
  assign _019_[18] = _002_[18] | _003_[18];
  assign _019_[19] = _002_[19] | _003_[19];
  assign _019_[20] = _002_[20] | _003_[20];
  assign _019_[21] = _002_[21] | _003_[21];
  assign _019_[22] = _002_[22] | _003_[22];
  assign _019_[23] = _002_[23] | _003_[23];
  assign _004_ = field_storage_r1_f_sqn6_7_value & _016_[23];
  assign _005_ = cpuif_wr_data[60] & cpuif_wr_biten[62];
  assign _020_ = _004_ | _005_;
  assign _006_[0] = field_storage_r2_f_unsigned_value[0] & _017_[7];
  assign _006_[1] = field_storage_r2_f_unsigned_value[1] & _017_[7];
  assign _006_[2] = field_storage_r2_f_unsigned_value[2] & _017_[7];
  assign _006_[3] = field_storage_r2_f_unsigned_value[3] & _017_[7];
  assign _006_[4] = field_storage_r2_f_unsigned_value[4] & _017_[7];
  assign _006_[5] = field_storage_r2_f_unsigned_value[5] & _017_[7];
  assign _006_[6] = field_storage_r2_f_unsigned_value[6] & _017_[7];
  assign _006_[7] = field_storage_r2_f_unsigned_value[7] & _017_[7];
  assign _006_[8] = field_storage_r2_f_unsigned_value[8] & _017_[15];
  assign _006_[9] = field_storage_r2_f_unsigned_value[9] & _017_[15];
  assign _006_[10] = field_storage_r2_f_unsigned_value[10] & _017_[15];
  assign _006_[11] = field_storage_r2_f_unsigned_value[11] & _017_[15];
  assign _006_[12] = field_storage_r2_f_unsigned_value[12] & _017_[15];
  assign _006_[13] = field_storage_r2_f_unsigned_value[13] & _017_[15];
  assign _006_[14] = field_storage_r2_f_unsigned_value[14] & _017_[15];
  assign _006_[15] = field_storage_r2_f_unsigned_value[15] & _017_[15];
  assign _007_[0] = cpuif_wr_data[16] & cpuif_wr_biten[22];
  assign _007_[1] = cpuif_wr_data[17] & cpuif_wr_biten[22];
  assign _007_[2] = cpuif_wr_data[18] & cpuif_wr_biten[22];
  assign _007_[3] = cpuif_wr_data[19] & cpuif_wr_biten[22];
  assign _007_[4] = cpuif_wr_data[20] & cpuif_wr_biten[22];
  assign _007_[5] = cpuif_wr_data[21] & cpuif_wr_biten[22];
  assign _007_[6] = cpuif_wr_data[22] & cpuif_wr_biten[22];
  assign _007_[7] = cpuif_wr_data[23] & cpuif_wr_biten[22];
  assign _007_[8] = cpuif_wr_data[24] & cpuif_wr_biten[30];
  assign _007_[9] = cpuif_wr_data[25] & cpuif_wr_biten[30];
  assign _007_[10] = cpuif_wr_data[26] & cpuif_wr_biten[30];
  assign _007_[11] = cpuif_wr_data[27] & cpuif_wr_biten[30];
  assign _007_[12] = cpuif_wr_data[28] & cpuif_wr_biten[30];
  assign _007_[13] = cpuif_wr_data[29] & cpuif_wr_biten[30];
  assign _007_[14] = cpuif_wr_data[30] & cpuif_wr_biten[30];
  assign _007_[15] = cpuif_wr_data[31] & cpuif_wr_biten[30];
  assign _021_[0] = _006_[0] | _007_[0];
  assign _021_[1] = _006_[1] | _007_[1];
  assign _021_[2] = _006_[2] | _007_[2];
  assign _021_[3] = _006_[3] | _007_[3];
  assign _021_[4] = _006_[4] | _007_[4];
  assign _021_[5] = _006_[5] | _007_[5];
  assign _021_[6] = _006_[6] | _007_[6];
  assign _021_[7] = _006_[7] | _007_[7];
  assign _021_[8] = _006_[8] | _007_[8];
  assign _021_[9] = _006_[9] | _007_[9];
  assign _021_[10] = _006_[10] | _007_[10];
  assign _021_[11] = _006_[11] | _007_[11];
  assign _021_[12] = _006_[12] | _007_[12];
  assign _021_[13] = _006_[13] | _007_[13];
  assign _021_[14] = _006_[14] | _007_[14];
  assign _021_[15] = _006_[15] | _007_[15];
  assign cpuif_wr_ack = cpuif_req & cpuif_req_is_wr;
  assign cpuif_rd_ack = cpuif_req & _014_;
  assign s_apb_prdata[0] = \readback_array[0] [0] | \readback_array[1] [0];
  assign s_apb_prdata[1] = \readback_array[0] [1] | \readback_array[1] [1];
  assign s_apb_prdata[2] = \readback_array[0] [2] | \readback_array[1] [2];
  assign s_apb_prdata[3] = \readback_array[0] [3] | \readback_array[1] [3];
  assign s_apb_prdata[4] = \readback_array[0] [4] | \readback_array[1] [4];
  assign s_apb_prdata[5] = \readback_array[0] [5] | \readback_array[1] [5];
  assign s_apb_prdata[6] = \readback_array[0] [6] | \readback_array[1] [6];
  assign s_apb_prdata[7] = \readback_array[0] [7] | \readback_array[1] [7];
  assign s_apb_prdata[8] = \readback_array[0] [8] | \readback_array[1] [8];
  assign s_apb_prdata[9] = \readback_array[0] [9] | \readback_array[1] [9];
  assign s_apb_prdata[10] = \readback_array[0] [10] | \readback_array[1] [10];
  assign s_apb_prdata[11] = \readback_array[0] [11] | \readback_array[1] [11];
  assign s_apb_prdata[12] = \readback_array[0] [12] | \readback_array[1] [12];
  assign s_apb_prdata[13] = \readback_array[0] [13] | \readback_array[1] [13];
  assign s_apb_prdata[14] = \readback_array[0] [14] | \readback_array[1] [14];
  assign s_apb_prdata[15] = \readback_array[0] [15] | \readback_array[1] [15];
  assign s_apb_prdata[16] = \readback_array[0] [16] | \readback_array[1] [16];
  assign s_apb_prdata[17] = \readback_array[0] [17] | \readback_array[1] [17];
  assign s_apb_prdata[18] = \readback_array[0] [18] | \readback_array[1] [18];
  assign s_apb_prdata[19] = \readback_array[0] [19] | \readback_array[1] [19];
  assign s_apb_prdata[20] = \readback_array[0] [20] | \readback_array[1] [20];
  assign s_apb_prdata[21] = \readback_array[0] [21] | \readback_array[1] [21];
  assign s_apb_prdata[22] = \readback_array[0] [22] | \readback_array[1] [22];
  assign s_apb_prdata[23] = \readback_array[0] [23] | \readback_array[1] [23];
  assign s_apb_prdata[24] = \readback_array[0] [24] | \readback_array[1] [24];
  assign s_apb_prdata[25] = \readback_array[0] [25] | \readback_array[1] [25];
  assign s_apb_prdata[26] = \readback_array[0] [26] | \readback_array[1] [26];
  assign s_apb_prdata[27] = \readback_array[0] [27] | \readback_array[1] [27];
  assign s_apb_prdata[28] = \readback_array[0] [28] | \readback_array[1] [28];
  assign s_apb_prdata[29] = \readback_array[0] [29] | \readback_array[1] [29];
  assign s_apb_prdata[30] = \readback_array[0] [30] | \readback_array[1] [30];
  assign s_apb_prdata[31] = \readback_array[0] [31] | \readback_array[1] [31];
  assign s_apb_prdata[32] = \readback_array[0] [32] | \readback_array[1] [32];
  assign s_apb_prdata[33] = \readback_array[0] [33] | \readback_array[1] [33];
  assign s_apb_prdata[34] = \readback_array[0] [34] | \readback_array[1] [34];
  assign s_apb_prdata[35] = \readback_array[0] [35] | \readback_array[1] [35];
  assign s_apb_prdata[36] = \readback_array[0] [36] | \readback_array[1] [36];
  assign s_apb_prdata[37] = \readback_array[0] [37] | \readback_array[1] [37];
  assign s_apb_prdata[38] = \readback_array[0] [38] | \readback_array[1] [38];
  assign s_apb_prdata[39] = \readback_array[0] [39] | \readback_array[1] [39];
  assign s_apb_prdata[40] = \readback_array[0] [40] | \readback_array[1] [40];
  assign s_apb_prdata[41] = \readback_array[0] [41] | \readback_array[1] [41];
  assign s_apb_prdata[42] = \readback_array[0] [42] | \readback_array[1] [42];
  assign s_apb_prdata[43] = \readback_array[0] [43] | \readback_array[1] [43];
  assign s_apb_prdata[44] = \readback_array[0] [44] | \readback_array[1] [44];
  assign s_apb_prdata[45] = \readback_array[0] [45] | \readback_array[1] [45];
  assign s_apb_prdata[46] = \readback_array[0] [46] | \readback_array[1] [46];
  assign s_apb_prdata[47] = \readback_array[0] [47] | \readback_array[1] [47];
  assign _008_ = s_apb_psel & _010_;
  assign _009_ = rst | is_active;
  assign _011_ = ~cpuif_addr[3];
  assign _014_ = ~cpuif_req_is_wr;
  assign s_apb_pready = cpuif_rd_ack | cpuif_wr_ack;
  assign field_combo_r1_f_q8_8_load_next = decoded_reg_strb_r1 & cpuif_req_is_wr;
  assign field_combo_r2_f_unsigned_load_next = decoded_reg_strb_r2 & cpuif_req_is_wr;
  assign _012_ = decoded_reg_strb_r1 & _014_;
  assign _013_ = decoded_reg_strb_r2 & _014_;
  assign \readback_array[0] [0] = _012_ ? field_storage_r1_f_q8_8_value[0] : 1'h0;
  assign \readback_array[0] [1] = _012_ ? field_storage_r1_f_q8_8_value[1] : 1'h0;
  assign \readback_array[0] [2] = _012_ ? field_storage_r1_f_q8_8_value[2] : 1'h0;
  assign \readback_array[0] [3] = _012_ ? field_storage_r1_f_q8_8_value[3] : 1'h0;
  assign \readback_array[0] [4] = _012_ ? field_storage_r1_f_q8_8_value[4] : 1'h0;
  assign \readback_array[0] [5] = _012_ ? field_storage_r1_f_q8_8_value[5] : 1'h0;
  assign \readback_array[0] [6] = _012_ ? field_storage_r1_f_q8_8_value[6] : 1'h0;
  assign \readback_array[0] [7] = _012_ ? field_storage_r1_f_q8_8_value[7] : 1'h0;
  assign \readback_array[0] [8] = _012_ ? field_storage_r1_f_q8_8_value[8] : 1'h0;
  assign \readback_array[0] [9] = _012_ ? field_storage_r1_f_q8_8_value[9] : 1'h0;
  assign \readback_array[0] [10] = _012_ ? field_storage_r1_f_q8_8_value[10] : 1'h0;
  assign \readback_array[0] [11] = _012_ ? field_storage_r1_f_q8_8_value[11] : 1'h0;
  assign \readback_array[0] [12] = _012_ ? field_storage_r1_f_q8_8_value[12] : 1'h0;
  assign \readback_array[0] [13] = _012_ ? field_storage_r1_f_q8_8_value[13] : 1'h0;
  assign \readback_array[0] [14] = _012_ ? field_storage_r1_f_q8_8_value[14] : 1'h0;
  assign \readback_array[0] [15] = _012_ ? field_storage_r1_f_q8_8_value[15] : 1'h0;
  assign \readback_array[0] [16] = _012_ ? hwif_in_r1_f_q32_n12[0] : 1'h0;
  assign \readback_array[0] [17] = _012_ ? hwif_in_r1_f_q32_n12[1] : 1'h0;
  assign \readback_array[0] [18] = _012_ ? hwif_in_r1_f_q32_n12[2] : 1'h0;
  assign \readback_array[0] [19] = _012_ ? hwif_in_r1_f_q32_n12[3] : 1'h0;
  assign \readback_array[0] [20] = _012_ ? hwif_in_r1_f_q32_n12[4] : 1'h0;
  assign \readback_array[0] [21] = _012_ ? hwif_in_r1_f_q32_n12[5] : 1'h0;
  assign \readback_array[0] [22] = _012_ ? hwif_in_r1_f_q32_n12[6] : 1'h0;
  assign \readback_array[0] [23] = _012_ ? hwif_in_r1_f_q32_n12[7] : 1'h0;
  assign \readback_array[0] [24] = _012_ ? hwif_in_r1_f_q32_n12[8] : 1'h0;
  assign \readback_array[0] [25] = _012_ ? hwif_in_r1_f_q32_n12[9] : 1'h0;
  assign \readback_array[0] [26] = _012_ ? hwif_in_r1_f_q32_n12[10] : 1'h0;
  assign \readback_array[0] [27] = _012_ ? hwif_in_r1_f_q32_n12[11] : 1'h0;
  assign \readback_array[0] [28] = _012_ ? hwif_in_r1_f_q32_n12[12] : 1'h0;
  assign \readback_array[0] [29] = _012_ ? hwif_in_r1_f_q32_n12[13] : 1'h0;
  assign \readback_array[0] [30] = _012_ ? hwif_in_r1_f_q32_n12[14] : 1'h0;
  assign \readback_array[0] [31] = _012_ ? hwif_in_r1_f_q32_n12[15] : 1'h0;
  assign \readback_array[0] [32] = _012_ ? hwif_in_r1_f_q32_n12[16] : 1'h0;
  assign \readback_array[0] [33] = _012_ ? hwif_in_r1_f_q32_n12[17] : 1'h0;
  assign \readback_array[0] [34] = _012_ ? hwif_in_r1_f_q32_n12[18] : 1'h0;
  assign \readback_array[0] [35] = _012_ ? hwif_in_r1_f_q32_n12[19] : 1'h0;
  assign \readback_array[0] [36] = _012_ ? field_storage_r1_f_sqn8_32_value[0] : 1'h0;
  assign \readback_array[0] [37] = _012_ ? field_storage_r1_f_sqn8_32_value[1] : 1'h0;
  assign \readback_array[0] [38] = _012_ ? field_storage_r1_f_sqn8_32_value[2] : 1'h0;
  assign \readback_array[0] [39] = _012_ ? field_storage_r1_f_sqn8_32_value[3] : 1'h0;
  assign \readback_array[0] [40] = _012_ ? field_storage_r1_f_sqn8_32_value[4] : 1'h0;
  assign \readback_array[0] [41] = _012_ ? field_storage_r1_f_sqn8_32_value[5] : 1'h0;
  assign \readback_array[0] [42] = _012_ ? field_storage_r1_f_sqn8_32_value[6] : 1'h0;
  assign \readback_array[0] [43] = _012_ ? field_storage_r1_f_sqn8_32_value[7] : 1'h0;
  assign \readback_array[0] [44] = _012_ ? field_storage_r1_f_sqn8_32_value[8] : 1'h0;
  assign \readback_array[0] [45] = _012_ ? field_storage_r1_f_sqn8_32_value[9] : 1'h0;
  assign \readback_array[0] [46] = _012_ ? field_storage_r1_f_sqn8_32_value[10] : 1'h0;
  assign \readback_array[0] [47] = _012_ ? field_storage_r1_f_sqn8_32_value[11] : 1'h0;
  assign \readback_array[0] [48] = _012_ ? field_storage_r1_f_sqn8_32_value[12] : 1'h0;
  assign \readback_array[0] [49] = _012_ ? field_storage_r1_f_sqn8_32_value[13] : 1'h0;
  assign \readback_array[0] [50] = _012_ ? field_storage_r1_f_sqn8_32_value[14] : 1'h0;
  assign \readback_array[0] [51] = _012_ ? field_storage_r1_f_sqn8_32_value[15] : 1'h0;
  assign \readback_array[0] [52] = _012_ ? field_storage_r1_f_sqn8_32_value[16] : 1'h0;
  assign \readback_array[0] [53] = _012_ ? field_storage_r1_f_sqn8_32_value[17] : 1'h0;
  assign \readback_array[0] [54] = _012_ ? field_storage_r1_f_sqn8_32_value[18] : 1'h0;
  assign \readback_array[0] [55] = _012_ ? field_storage_r1_f_sqn8_32_value[19] : 1'h0;
  assign \readback_array[0] [56] = _012_ ? field_storage_r1_f_sqn8_32_value[20] : 1'h0;
  assign \readback_array[0] [57] = _012_ ? field_storage_r1_f_sqn8_32_value[21] : 1'h0;
  assign \readback_array[0] [58] = _012_ ? field_storage_r1_f_sqn8_32_value[22] : 1'h0;
  assign \readback_array[0] [59] = _012_ ? field_storage_r1_f_sqn8_32_value[23] : 1'h0;
  assign \readback_array[0] [60] = _012_ ? field_storage_r1_f_sqn6_7_value : 1'h0;
  assign \readback_array[1] [0] = _013_ ? hwif_in_r2_f_signed[0] : 1'h0;
  assign \readback_array[1] [1] = _013_ ? hwif_in_r2_f_signed[1] : 1'h0;
  assign \readback_array[1] [2] = _013_ ? hwif_in_r2_f_signed[2] : 1'h0;
  assign \readback_array[1] [3] = _013_ ? hwif_in_r2_f_signed[3] : 1'h0;
  assign \readback_array[1] [4] = _013_ ? hwif_in_r2_f_signed[4] : 1'h0;
  assign \readback_array[1] [5] = _013_ ? hwif_in_r2_f_signed[5] : 1'h0;
  assign \readback_array[1] [6] = _013_ ? hwif_in_r2_f_signed[6] : 1'h0;
  assign \readback_array[1] [7] = _013_ ? hwif_in_r2_f_signed[7] : 1'h0;
  assign \readback_array[1] [8] = _013_ ? hwif_in_r2_f_signed[8] : 1'h0;
  assign \readback_array[1] [9] = _013_ ? hwif_in_r2_f_signed[9] : 1'h0;
  assign \readback_array[1] [10] = _013_ ? hwif_in_r2_f_signed[10] : 1'h0;
  assign \readback_array[1] [11] = _013_ ? hwif_in_r2_f_signed[11] : 1'h0;
  assign \readback_array[1] [12] = _013_ ? hwif_in_r2_f_signed[12] : 1'h0;
  assign \readback_array[1] [13] = _013_ ? hwif_in_r2_f_signed[13] : 1'h0;
  assign \readback_array[1] [14] = _013_ ? hwif_in_r2_f_signed[14] : 1'h0;
  assign \readback_array[1] [15] = _013_ ? hwif_in_r2_f_signed[15] : 1'h0;
  assign \readback_array[1] [16] = _013_ ? field_storage_r2_f_unsigned_value[0] : 1'h0;
  assign \readback_array[1] [17] = _013_ ? field_storage_r2_f_unsigned_value[1] : 1'h0;
  assign \readback_array[1] [18] = _013_ ? field_storage_r2_f_unsigned_value[2] : 1'h0;
  assign \readback_array[1] [19] = _013_ ? field_storage_r2_f_unsigned_value[3] : 1'h0;
  assign \readback_array[1] [20] = _013_ ? field_storage_r2_f_unsigned_value[4] : 1'h0;
  assign \readback_array[1] [21] = _013_ ? field_storage_r2_f_unsigned_value[5] : 1'h0;
  assign \readback_array[1] [22] = _013_ ? field_storage_r2_f_unsigned_value[6] : 1'h0;
  assign \readback_array[1] [23] = _013_ ? field_storage_r2_f_unsigned_value[7] : 1'h0;
  assign \readback_array[1] [24] = _013_ ? field_storage_r2_f_unsigned_value[8] : 1'h0;
  assign \readback_array[1] [25] = _013_ ? field_storage_r2_f_unsigned_value[9] : 1'h0;
  assign \readback_array[1] [26] = _013_ ? field_storage_r2_f_unsigned_value[10] : 1'h0;
  assign \readback_array[1] [27] = _013_ ? field_storage_r2_f_unsigned_value[11] : 1'h0;
  assign \readback_array[1] [28] = _013_ ? field_storage_r2_f_unsigned_value[12] : 1'h0;
  assign \readback_array[1] [29] = _013_ ? field_storage_r2_f_unsigned_value[13] : 1'h0;
  assign \readback_array[1] [30] = _013_ ? field_storage_r2_f_unsigned_value[14] : 1'h0;
  assign \readback_array[1] [31] = _013_ ? field_storage_r2_f_unsigned_value[15] : 1'h0;
  assign \readback_array[1] [32] = _013_ ? hwif_in_r2_f_no_sign[0] : 1'h0;
  assign \readback_array[1] [33] = _013_ ? hwif_in_r2_f_no_sign[1] : 1'h0;
  assign \readback_array[1] [34] = _013_ ? hwif_in_r2_f_no_sign[2] : 1'h0;
  assign \readback_array[1] [35] = _013_ ? hwif_in_r2_f_no_sign[3] : 1'h0;
  assign \readback_array[1] [36] = _013_ ? hwif_in_r2_f_no_sign[4] : 1'h0;
  assign \readback_array[1] [37] = _013_ ? hwif_in_r2_f_no_sign[5] : 1'h0;
  assign \readback_array[1] [38] = _013_ ? hwif_in_r2_f_no_sign[6] : 1'h0;
  assign \readback_array[1] [39] = _013_ ? hwif_in_r2_f_no_sign[7] : 1'h0;
  assign \readback_array[1] [40] = _013_ ? hwif_in_r2_f_no_sign[8] : 1'h0;
  assign \readback_array[1] [41] = _013_ ? hwif_in_r2_f_no_sign[9] : 1'h0;
  assign \readback_array[1] [42] = _013_ ? hwif_in_r2_f_no_sign[10] : 1'h0;
  assign \readback_array[1] [43] = _013_ ? hwif_in_r2_f_no_sign[11] : 1'h0;
  assign \readback_array[1] [44] = _013_ ? hwif_in_r2_f_no_sign[12] : 1'h0;
  assign \readback_array[1] [45] = _013_ ? hwif_in_r2_f_no_sign[13] : 1'h0;
  assign \readback_array[1] [46] = _013_ ? hwif_in_r2_f_no_sign[14] : 1'h0;
  assign \readback_array[1] [47] = _013_ ? hwif_in_r2_f_no_sign[15] : 1'h0;
  assign _022_ = ~s_apb_pready;
  assign _023_ = is_active ? _022_ : s_apb_psel;
  assign _010_ = ~is_active;
  assign _015_[7] = ~cpuif_wr_biten[5];
  assign _015_[15] = ~cpuif_wr_biten[14];
  assign _016_[3] = ~cpuif_wr_biten[38];
  assign _016_[11] = ~cpuif_wr_biten[46];
  assign _016_[19] = ~cpuif_wr_biten[54];
  assign _016_[23] = ~cpuif_wr_biten[62];
  assign _017_[7] = ~cpuif_wr_biten[22];
  assign _017_[15] = ~cpuif_wr_biten[30];
  assign { _015_[14:8], _015_[6:0] } = { _015_[15], _015_[15], _015_[15], _015_[15], _015_[15], _015_[15], _015_[15], _015_[7], _015_[7], _015_[7], _015_[7], _015_[7], _015_[7], _015_[7] };
  assign { _016_[22:20], _016_[18:12], _016_[10:4], _016_[2:0] } = { _016_[23], _016_[23], _016_[23], _016_[19], _016_[19], _016_[19], _016_[19], _016_[19], _016_[19], _016_[19], _016_[11], _016_[11], _016_[11], _016_[11], _016_[11], _016_[11], _016_[11], _016_[3], _016_[3], _016_[3] };
  assign { _017_[14:8], _017_[6:0] } = { _017_[15], _017_[15], _017_[15], _017_[15], _017_[15], _017_[15], _017_[15], _017_[7], _017_[7], _017_[7], _017_[7], _017_[7], _017_[7], _017_[7] };
  assign cpuif_addr[2:0] = 3'h0;
  assign cpuif_rd_data = { 3'h0, \readback_array[0] [60:48], s_apb_prdata[47:0] };
  assign cpuif_rd_err = 1'h0;
  assign cpuif_req_masked = cpuif_req;
  assign cpuif_req_stall_rd = 1'h0;
  assign cpuif_req_stall_wr = 1'h0;
  assign { cpuif_wr_biten[63], cpuif_wr_biten[61:55], cpuif_wr_biten[53:47], cpuif_wr_biten[45:39], cpuif_wr_biten[37:31], cpuif_wr_biten[29:23], cpuif_wr_biten[21:15], cpuif_wr_biten[13:6], cpuif_wr_biten[4:0] } = { cpuif_wr_biten[62], cpuif_wr_biten[62], cpuif_wr_biten[62], cpuif_wr_biten[62], cpuif_wr_biten[62], cpuif_wr_biten[62], cpuif_wr_biten[62], cpuif_wr_biten[54], cpuif_wr_biten[54], cpuif_wr_biten[54], cpuif_wr_biten[54], cpuif_wr_biten[54], cpuif_wr_biten[54], cpuif_wr_biten[54], cpuif_wr_biten[46], cpuif_wr_biten[46], cpuif_wr_biten[46], cpuif_wr_biten[46], cpuif_wr_biten[46], cpuif_wr_biten[46], cpuif_wr_biten[46], cpuif_wr_biten[38], cpuif_wr_biten[38], cpuif_wr_biten[38], cpuif_wr_biten[38], cpuif_wr_biten[38], cpuif_wr_biten[38], cpuif_wr_biten[38], cpuif_wr_biten[30], cpuif_wr_biten[30], cpuif_wr_biten[30], cpuif_wr_biten[30], cpuif_wr_biten[30], cpuif_wr_biten[30], cpuif_wr_biten[30], cpuif_wr_biten[22], cpuif_wr_biten[22], cpuif_wr_biten[22], cpuif_wr_biten[22], cpuif_wr_biten[22], cpuif_wr_biten[22], cpuif_wr_biten[22], cpuif_wr_biten[14], cpuif_wr_biten[14], cpuif_wr_biten[14], cpuif_wr_biten[14], cpuif_wr_biten[14], cpuif_wr_biten[14], cpuif_wr_biten[14], cpuif_wr_biten[5], cpuif_wr_biten[5], cpuif_wr_biten[5], cpuif_wr_biten[5], cpuif_wr_biten[5], cpuif_wr_biten[5], cpuif_wr_biten[5] };
  assign cpuif_wr_err = 1'h0;
  assign decoded_req = cpuif_req;
  assign decoded_req_is_wr = cpuif_req_is_wr;
  assign decoded_wr_biten = { cpuif_wr_biten[62], cpuif_wr_biten[62], cpuif_wr_biten[62], cpuif_wr_biten[62], cpuif_wr_biten[62], cpuif_wr_biten[62], cpuif_wr_biten[62], cpuif_wr_biten[62], cpuif_wr_biten[54], cpuif_wr_biten[54], cpuif_wr_biten[54], cpuif_wr_biten[54], cpuif_wr_biten[54], cpuif_wr_biten[54], cpuif_wr_biten[54], cpuif_wr_biten[54], cpuif_wr_biten[46], cpuif_wr_biten[46], cpuif_wr_biten[46], cpuif_wr_biten[46], cpuif_wr_biten[46], cpuif_wr_biten[46], cpuif_wr_biten[46], cpuif_wr_biten[46], cpuif_wr_biten[38], cpuif_wr_biten[38], cpuif_wr_biten[38], cpuif_wr_biten[38], cpuif_wr_biten[38], cpuif_wr_biten[38], cpuif_wr_biten[38], cpuif_wr_biten[38], cpuif_wr_biten[30], cpuif_wr_biten[30], cpuif_wr_biten[30], cpuif_wr_biten[30], cpuif_wr_biten[30], cpuif_wr_biten[30], cpuif_wr_biten[30], cpuif_wr_biten[30], cpuif_wr_biten[22], cpuif_wr_biten[22], cpuif_wr_biten[22], cpuif_wr_biten[22], cpuif_wr_biten[22], cpuif_wr_biten[22], cpuif_wr_biten[22], cpuif_wr_biten[22], cpuif_wr_biten[14], cpuif_wr_biten[14], cpuif_wr_biten[14], cpuif_wr_biten[14], cpuif_wr_biten[14], cpuif_wr_biten[14], cpuif_wr_biten[14], cpuif_wr_biten[14], cpuif_wr_biten[5], cpuif_wr_biten[5], cpuif_wr_biten[5], cpuif_wr_biten[5], cpuif_wr_biten[5], cpuif_wr_biten[5], cpuif_wr_biten[5], cpuif_wr_biten[5] };
  assign decoded_wr_data = cpuif_wr_data;
  assign field_combo_r1_f_sqn6_7_load_next = field_combo_r1_f_q8_8_load_next;
  assign field_combo_r1_f_sqn8_32_load_next = field_combo_r1_f_q8_8_load_next;
  assign hwif_out_r1_f_q8_8 = field_storage_r1_f_q8_8_value;
  assign hwif_out_r1_f_sqn6_7 = field_storage_r1_f_sqn6_7_value;
  assign hwif_out_r1_f_sqn8_32 = field_storage_r1_f_sqn8_32_value;
  assign hwif_out_r2_f_unsigned = field_storage_r2_f_unsigned_value;
  assign \readback_array[0] [63:61] = 3'h0;
  assign \readback_array[1] [63:48] = 16'h0000;
  assign readback_data = { 3'h0, \readback_array[0] [60:48], s_apb_prdata[47:0] };
  assign readback_done = cpuif_rd_ack;
  assign readback_err = 1'h0;
  assign readback_external_rd_ack = 1'h0;
  assign s_apb_prdata[63:48] = { 3'h0, \readback_array[0] [60:48] };
  assign s_apb_pslverr = 1'h0;
endmodule
